### ISSUE TITLE
file system scans fail with Cannot have multiple MGS mounts on host

### ISSUE THREAD

**Issue by kpoirier** [whamcloud/integrated-manager-for-lustre#1029]
**Scan for lustre targets fail on file systems with multiple MDS nodes/MDTs**

**To Reproduce**
Installed Fresh copy of IML 5.0.0-7 on new server, configure and add servers.
Scan file system with multiple MDS nodes with 2 MDTs running.

**Expected behavior**
The scan on another file system with a single mdt/mgt works without issue.

### Version
What version of IML? 5.0.0-7
What Operating System? Centos 
What Operating System version? 7.6
Lustre:  lustre-2.12.0-1.el7

Backtrace info:
```
Traceback (most recent call last):
  File "/usr/share/chroma-manager/chroma_core/services/job_scheduler/job_scheduler.py", line 326, in _run
    result = step.run(args)
  File "/usr/share/chroma-manager/chroma_core/models/host.py", line 988, in run
    DetectScan(self).run(host_data)
  File "/usr/share/chroma-manager/chroma_core/lib/detection.py", line 54, in run
    self.learn_target_mounts()
  File "/usr/share/chroma-manager/chroma_core/lib/detection.py", line 289, in learn_target_mounts
    target=target, host=host, volume_node=volumenode
  File "/usr/lib/python2.7/site-packages/django/db/models/manager.py", line 154, in get_or_create
    return self.get_queryset().get_or_create(**kwargs)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 383, in get_or_create
    obj.save(force_insert=True, using=self.db)
  File "/usr/share/chroma-manager/chroma_core/models/target.py", line 1776, in save
    raise ValidationError("Cannot have multiple MGS mounts on host %s" % self.host.address)
ValidationError: [u'**Cannot have multiple MGS mounts on host atheon-mdsdata1**']
```

### sosreport

[sosreport-atheon-mdsdata1-2019-07-02-xyasdef.tar.xz.gz](https://github.com/whamcloud/integrated-manager-for-lustre/files/3350024/sosreport-atheon-mdsdata1-2019-07-02-xyasdef.tar.xz.gz)

**Comment by kpoirier** [comment]
Do you need more information to troubleshoot this issue?  This still fails on detecting a file system with multiple MDS nodes.

**Comment by jgrund** [comment]
@kpoirier Do you already have a MGT detected? If you go to <MANAGER_URL_HERE>/ui/configure/mgt do you see a MGT there?
