### ISSUE TITLE
SSI test failure remote_operations.clear_ha paramiko socket.timeout

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#1127]
This appears to be the most common SSI test failure. 

```
Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_hsm.py", line 83, in setUp
    super(ManagedCopytoolTestCase, self).setUp()
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 66, in setUp
    self.reset_cluster()
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 533, in reset_cluster
    self.remote_operations.clear_ha(self.TEST_SERVERS)
  File "/usr/share/chroma-manager/tests/integration/core/remote_operations.py", line 941, in clear_ha
    address, "ring0_iface=%s\n%s" % (server["corosync_config"]["ring1_iface"], clear_ha_script.read())
  File "/usr/share/chroma-manager/tests/integration/core/remote_operations.py", line 225, in _ssh_address
    stdout = channel.makefile("rb").read()
  File "/usr/lib/python2.7/site-packages/paramiko/file.py", line 192, in read
    new_data = self._read(self._DEFAULT_BUFSIZE)
  File "/usr/lib/python2.7/site-packages/paramiko/channel.py", line 1292, in _read
    return self.channel.recv(size)
  File "/usr/lib/python2.7/site-packages/paramiko/channel.py", line 667, in recv
    raise socket.timeout()
timeout: 
```

The timeout appears to be 10 minutes.

**Comment by jgrund** [comment]
Something in this script triggers the hang:

https://github.com/whamcloud/integrated-manager-for-lustre/blob/ad82242259f9bce566c31a4aaf5f187379554fcf/tests/integration/core/clear_ha_el7.sh#L5-L23

**Comment by jgrund** [comment]
Relevant output from the hung node

```
Aug 08 07:05:12 vm7 sshd[23694]: Accepted publickey for root from 10.73.10.8 port 51130 ssh2: RSA SHA256:tNFErK9n4raQc29G7PvboupvIJXbS5
Aug 08 07:05:12 vm7 systemd[1]: Created slice User Slice of root.
-- Subject: Unit user-0.slice has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit user-0.slice has finished starting up.
--
-- The start-up result is done.
Aug 08 07:05:12 vm7 systemd[1]: Started Session 1265 of user root.
-- Subject: Unit session-1265.scope has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit session-1265.scope has finished starting up.
--
-- The start-up result is done.
Aug 08 07:05:12 vm7 systemd-logind[806]: New session 1265 of user root.
-- Subject: A new session 1265 has been created for user root
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: http://www.freedesktop.org/wiki/Software/systemd/multiseat
--
-- A new session with the ID 1265 has been created for the user root.
--
-- The leading process of the session is 23694.
Aug 08 07:05:12 vm7 sshd[23694]: pam_unix(sshd:session): session opened for user root by (uid=0)
Aug 08 07:05:12 vm7 sshd[23694]: pam_unix(sshd:session): session closed for user root
Aug 08 07:05:12 vm7 systemd-logind[806]: Removed session 1265.
-- Subject: Session 1265 has been terminated
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: http://www.freedesktop.org/wiki/Software/systemd/multiseat
--
-- A session with the ID 1265 has been terminated.
Aug 08 07:05:12 vm7 systemd[1]: Removed slice User Slice of root.
-- Subject: Unit user-0.slice has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit user-0.slice has finished shutting down.
Aug 08 07:05:12 vm7 sshd[23706]: Accepted publickey for root from 10.73.10.8 port 51132 ssh2: RSA SHA256:tNFErK9n4raQc29G7PvboupvIJXbS5
Aug 08 07:05:12 vm7 systemd[1]: Created slice User Slice of root.
-- Subject: Unit user-0.slice has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit user-0.slice has finished starting up.
--
-- The start-up result is done.
Aug 08 07:05:12 vm7 systemd[1]: Started Session 1266 of user root.
-- Subject: Unit session-1266.scope has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit session-1266.scope has finished starting up.
--
-- The start-up result is done.
Aug 08 07:05:12 vm7 systemd-logind[806]: New session 1266 of user root.
-- Subject: A new session 1266 has been created for user root
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: http://www.freedesktop.org/wiki/Software/systemd/multiseat
--
-- A new session with the ID 1266 has been created for the user root.
--
-- The leading process of the session is 23706.
Aug 08 07:05:12 vm7 sshd[23706]: pam_unix(sshd:session): session opened for user root by (uid=0)
Aug 08 07:05:13 vm7 pacemakerd[22600]:   notice: Caught 'Terminated' signal
Aug 08 07:05:13 vm7 systemd[1]: Stopping Pacemaker High Availability Cluster Manager...
-- Subject: Unit pacemaker.service has begun shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit pacemaker.service has begun shutting down.
Aug 08 07:05:13 vm7 pacemakerd[22600]:   notice: Shutting down Pacemaker
Aug 08 07:05:13 vm7 pacemakerd[22600]:   notice: Stopping crmd
Aug 08 07:05:13 vm7 crmd[22606]:   notice: Caught 'Terminated' signal
Aug 08 07:05:13 vm7 crmd[22606]:   notice: Shutting down cluster resource manager
Aug 08 07:10:01 vm7 systemd[1]: Started Session 1267 of user root.
-- Subject: Unit session-1267.scope has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit session-1267.scope has finished starting up.
--
-- The start-up result is done.
Aug 08 07:10:01 vm7 CROND[23784]: (root) CMD (/usr/lib64/sa/sa1 1 1)
Aug 08 07:15:13 vm7 sshd[23706]: pam_unix(sshd:session): session closed for user root
Aug 08 07:17:49 vm7 sshd[23838]: Accepted publickey for root from 192.168.121.1 port 39002 ssh2: RSA SHA256:WRH+2GLoZZtaJmJMoRAN/Imouxy
Aug 08 07:17:49 vm7 systemd[1]: Started Session 1268 of user root.
-- Subject: Unit session-1268.scope has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit session-1268.scope has finished starting up.
--
-- The start-up result is done.
Aug 08 07:17:49 vm7 systemd-logind[806]: New session 1268 of user root.
-- Subject: A new session 1268 has been created for user root
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: http://www.freedesktop.org/wiki/Software/systemd/multiseat
--
-- A new session with the ID 1268 has been created for the user root.
--
-- The leading process of the session is 23838.
Aug 08 07:17:49 vm7 sshd[23838]: pam_unix(sshd:session): session opened for user root by (uid=0)
Aug 08 07:17:49 vm7 sshd[23838]: Received disconnect from 192.168.121.1 port 39002:11: disconnected by user
Aug 08 07:17:49 vm7 sshd[23838]: Disconnected from 192.168.121.1 port 39002
Aug 08 07:17:49 vm7 sshd[23838]: pam_unix(sshd:session): session closed for user root
Aug 08 07:17:49 vm7 systemd-logind[806]: Removed session 1268.
-- Subject: Session 1268 has been terminated
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: http://www.freedesktop.org/wiki/Software/systemd/multiseat
--
-- A session with the ID 1268 has been terminated.
Aug 08 07:17:50 vm7 sshd[23844]: Accepted publickey for root from 192.168.121.1 port 39004 ssh2: RSA SHA256:WRH+2GLoZZtaJmJMoRAN/ImouxysOx+qNSw9462zMZM
Aug 08 07:17:50 vm7 systemd[1]: Started Session 1269 of user root.
-- Subject: Unit session-1269.scope has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit session-1269.scope has finished starting up.
--
-- The start-up result is done.
Aug 08 07:17:50 vm7 systemd-logind[806]: New session 1269 of user root.
-- Subject: A new session 1269 has been created for user root
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: http://www.freedesktop.org/wiki/Software/systemd/multiseat
--
-- A new session with the ID 1269 has been created for the user root.
--
-- The leading process of the session is 23844.
Aug 08 07:17:50 vm7 sshd[23844]: pam_unix(sshd:session): session opened for user root by (uid=0)
Aug 08 07:17:51 vm7 sshd[23844]: Received disconnect from 192.168.121.1 port 39004:11: disconnected by user
Aug 08 07:17:51 vm7 sshd[23844]: Disconnected from 192.168.121.1 port 39004
Aug 08 07:17:51 vm7 sshd[23844]: pam_unix(sshd:session): session closed for user root
Aug 08 07:17:51 vm7 systemd-logind[806]: Removed session 1269.
-- Subject: Session 1269 has been terminated
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: http://www.freedesktop.org/wiki/Software/systemd/multiseat
--
-- A session with the ID 1269 has been terminated.
Aug 08 07:17:51 vm7 sshd[23850]: Accepted publickey for root from 192.168.121.1 port 39006 ssh2: RSA SHA256:WRH+2GLoZZtaJmJMoRAN/ImouxysOx+qNSw9462zMZM
Aug 08 07:17:51 vm7 systemd[1]: Started Session 1270 of user root.
-- Subject: Unit session-1270.scope has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit session-1270.scope has finished starting up.
--
-- The start-up result is done.
Aug 08 07:17:51 vm7 systemd-logind[806]: New session 1270 of user root.
-- Subject: A new session 1270 has been created for user root
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: http://www.freedesktop.org/wiki/Software/systemd/multiseat
--
-- A new session with the ID 1270 has been created for the user root.
--
-- The leading process of the session is 23850.
Aug 08 07:17:51 vm7 sshd[23850]: pam_unix(sshd:session): session opened for user root by (uid=0)
Aug 08 07:17:55 vm7 crontab[24548]: (root) LIST (root)
Aug 08 07:17:55 vm7 qb_blackbox[24565]: [debug] shm size:8392704; real_size:8392704; rb->word_size:2098176
Aug 08 07:17:55 vm7 qb_blackbox[24565]: [debug] read total of: 8392724
Aug 08 07:17:55 vm7 qb_blackbox[24565]: [debug] Free'ing ringbuffer: /dev/shm/qb-create_from_file-header
Aug 08 07:17:56 vm7 kernel:  sdb: sdb1 sdb9
Aug 08 07:17:56 vm7 kernel: device-mapper: uevent: version 1.0.3
Aug 08 07:17:56 vm7 kernel: device-mapper: ioctl: 4.37.1-ioctl (2018-04-03) initialised: dm-devel@redhat.com
Aug 08 07:17:56 vm7 kernel:  sdd: sdd1 sdd9
Aug 08 07:17:56 vm7 dracut[24843]: dracut-033-554.el7
Aug 08 07:17:56 vm7 kernel:  sdf: sdf1 sdf9
Aug 08 07:17:56 vm7 dracut[24854]: Executing: /usr/sbin/dracut --list-modules
Aug 08 07:17:57 vm7 dbus[818]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service'
Aug 08 07:17:57 vm7 systemd[1]: Starting Hostname Service...
-- Subject: Unit systemd-hostnamed.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit systemd-hostnamed.service has begun starting up.
Aug 08 07:17:57 vm7 dbus[818]: [system] Successfully activated service 'org.freedesktop.hostname1'
Aug 08 07:17:57 vm7 systemd[1]: Started Hostname Service.
-- Subject: Unit systemd-hostnamed.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit systemd-hostnamed.service has finished starting up.
--
-- The start-up result is done.
Aug 08 07:17:59 vm7 systemd[1]: Got automount request for /proc/sys/fs/binfmt_misc, triggered by 26029 (sysctl)
Aug 08 07:17:59 vm7 systemd[1]: Mounting Arbitrary Executable File Formats File System...
-- Subject: Unit proc-sys-fs-binfmt_misc.mount has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit proc-sys-fs-binfmt_misc.mount has begun starting up.
Aug 08 07:17:59 vm7 systemd[1]: Mounted Arbitrary Executable File Formats File System.
-- Subject: Unit proc-sys-fs-binfmt_misc.mount has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit proc-sys-fs-binfmt_misc.mount has finished starting up.
--
-- The start-up result is done.
Aug 08 07:17:59 vm7 kernel: nr_pdflush_threads exported in /proc is scheduled for removal
Aug 08 07:18:00 vm7 kernel: MACsec IEEE 802.1AE
Aug 08 07:18:01 vm7 kernel: warning: `turbostat' uses 32-bit capabilities (legacy support in use)
Aug 08 07:18:04 vm7 dbus[818]: [system] Activating via systemd: service name='org.freedesktop.timedate1' unit='dbus-org.freedesktop.timedate1.service'
Aug 08 07:18:04 vm7 systemd[1]: Starting Time & Date Service...
-- Subject: Unit systemd-timedated.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit systemd-timedated.service has begun starting up.
Aug 08 07:18:04 vm7 dbus[818]: [system] Successfully activated service 'org.freedesktop.timedate1'
Aug 08 07:18:04 vm7 systemd[1]: Started Time & Date Service.
-- Subject: Unit systemd-timedated.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit systemd-timedated.service has finished starting up.
--
-- The start-up result is done.
Aug 08 07:18:07 vm7 qb_blackbox[27330]: [debug] shm size:8392704; real_size:8392704; rb->word_size:2098176
Aug 08 07:18:07 vm7 qb_blackbox[27330]: [debug] read total of: 8392724
Aug 08 07:18:07 vm7 qb_blackbox[27330]: [debug] Free'ing ringbuffer: /dev/shm/qb-create_from_file-header
Aug 08 07:18:35 vm7 sshd[23850]: Received disconnect from 192.168.121.1 port 39006:11: disconnected by user
Aug 08 07:18:35 vm7 sshd[23850]: Disconnected from 192.168.121.1 port 39006
Aug 08 07:18:35 vm7 sshd[23850]: pam_unix(sshd:session): session closed for user root
Aug 08 07:18:35 vm7 systemd-logind[806]: Removed session 1270.
-- Subject: Session 1270 has been terminated
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: http://www.freedesktop.org/wiki/Software/systemd/multiseat
--
-- A session with the ID 1270 has been terminated.
Aug 08 07:18:35 vm7 sshd[27756]: Accepted publickey for root from 192.168.121.1 port 39008 ssh2: RSA SHA256:WRH+2GLoZZtaJmJMoRAN/ImouxysOx+qNSw9462zMZM
Aug 08 07:18:35 vm7 systemd[1]: Started Session 1271 of user root.
-- Subject: Unit session-1271.scope has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit session-1271.scope has finished starting up.
--
-- The start-up result is done.
Aug 08 07:18:35 vm7 systemd-logind[806]: New session 1271 of user root.
-- Subject: A new session 1271 has been created for user root
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: http://www.freedesktop.org/wiki/Software/systemd/multiseat
--
-- A new session with the ID 1271 has been created for the user root.
--
-- The leading process of the session is 27756.
Aug 08 07:18:35 vm7 sshd[27756]: pam_unix(sshd:session): session opened for user root by (uid=0)
Aug 08 07:18:36 vm7 sshd[27756]: Received disconnect from 192.168.121.1 port 39008:11: disconnected by user
Aug 08 07:18:36 vm7 sshd[27756]: Disconnected from 192.168.121.1 port 39008
Aug 08 07:18:36 vm7 sshd[27756]: pam_unix(sshd:session): session closed for user root
Aug 08 07:18:36 vm7 systemd-logind[806]: Removed session 1271.
-- Subject: Session 1271 has been terminated
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: http://www.freedesktop.org/wiki/Software/systemd/multiseat
--
-- A session with the ID 1271 has been terminated.
Aug 08 07:20:01 vm7 systemd[1]: Started Session 1272 of user root.
-- Subject: Unit session-1272.scope has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit session-1272.scope has finished starting up.
--
-- The start-up result is done.
Aug 08 07:20:01 vm7 CROND[27839]: (root) CMD (/usr/lib64/sa/sa1 1 1)
Aug 08 07:25:13 vm7 crmd[22606]:    error: Shutdown Escalation (I_STOP) just popped in state S_NOT_DC! (1200000ms)
Aug 08 07:25:13 vm7 crmd[22606]:   notice: State transition S_NOT_DC -> S_STOPPING
Aug 08 07:25:13 vm7 crmd[22606]:    error: 1 resource was active at shutdown
Aug 08 07:25:13 vm7 crmd[22606]:   notice: Disconnected from the LRM
Aug 08 07:25:13 vm7 crmd[22606]:   notice: Disconnected from Corosync
Aug 08 07:25:13 vm7 crmd[22606]:   notice: Disconnected from the CIB
Aug 08 07:25:13 vm7 attrd[22604]:   notice: Node vm8 state is now lost
Aug 08 07:25:13 vm7 attrd[22604]:   notice: Removing all vm8 attributes for peer loss
Aug 08 07:25:13 vm7 attrd[22604]:   notice: Lost attribute writer vm8
Aug 08 07:25:13 vm7 attrd[22604]:   notice: Purged 1 peer with id=2 and/or uname=vm8 from the membership cache
Aug 08 07:25:13 vm7 pengine[22605]:   notice: Caught 'Terminated' signal
Aug 08 07:25:13 vm7 pacemakerd[22600]:   notice: Stopping pengine
Aug 08 07:25:13 vm7 pacemakerd[22600]:   notice: Stopping attrd
Aug 08 07:25:13 vm7 attrd[22604]:   notice: Caught 'Terminated' signal
Aug 08 07:25:13 vm7 pacemakerd[22600]:   notice: Stopping lrmd
Aug 08 07:25:13 vm7 lrmd[22603]:   notice: Caught 'Terminated' signal
Aug 08 07:25:13 vm7 stonith-ng[22602]:   notice: Node vm8 state is now lost
Aug 08 07:25:13 vm7 stonith-ng[22602]:   notice: Purged 1 peer with id=2 and/or uname=vm8 from the membership cache
Aug 08 07:25:13 vm7 cib[22601]:   notice: Node vm8 state is now lost
Aug 08 07:25:13 vm7 cib[22601]:   notice: Purged 1 peer with id=2 and/or uname=vm8 from the membership cache
Aug 08 07:25:13 vm7 stonith-ng[22602]:   notice: Caught 'Terminated' signal
Aug 08 07:25:13 vm7 pacemakerd[22600]:   notice: Stopping stonith-ng
Aug 08 07:25:13 vm7 pacemakerd[22600]:   notice: Stopping cib
Aug 08 07:25:13 vm7 cib[22601]:   notice: Caught 'Terminated' signal
Aug 08 07:25:13 vm7 cib[22601]:   notice: Disconnected from Corosync
Aug 08 07:25:13 vm7 cib[22601]:   notice: Disconnected from Corosync
Aug 08 07:25:13 vm7 pacemakerd[22600]:   notice: Shutdown complete
Aug 08 07:25:13 vm7 systemd[1]: Stopped Pacemaker High Availability Cluster Manager.
-- Subject: Unit pacemaker.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit pacemaker.service has finished shutting down.
Aug 08 07:25:14 vm7 systemd[1]: Stopping Corosync Cluster Engine...
-- Subject: Unit corosync.service has begun shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit corosync.service has begun shutting down.
Aug 08 07:25:14 vm7 corosync[21754]:  [MAIN  ] Node was shut down by a signal
Aug 08 07:25:14 vm7 corosync[28134]: Signaling Corosync Cluster Engine (corosync) to terminate: [  OK  ]
Aug 08 07:25:14 vm7 corosync[21754]:  [SERV  ] Unloading all Corosync service engines.
Aug 08 07:25:14 vm7 corosync[21754]:  [QB    ] withdrawing server sockets
Aug 08 07:25:14 vm7 corosync[21754]:  [SERV  ] Service engine unloaded: corosync vote quorum service v1.0
Aug 08 07:25:14 vm7 corosync[21754]:  [QB    ] withdrawing server sockets
Aug 08 07:25:14 vm7 corosync[21754]:  [SERV  ] Service engine unloaded: corosync configuration map access
Aug 08 07:25:14 vm7 corosync[21754]:  [QB    ] withdrawing server sockets
Aug 08 07:25:14 vm7 corosync[21754]:  [SERV  ] Service engine unloaded: corosync configuration service
Aug 08 07:25:14 vm7 corosync[21754]:  [QB    ] withdrawing server sockets
Aug 08 07:25:14 vm7 corosync[21754]:  [SERV  ] Service engine unloaded: corosync cluster closed process group service v1.01
Aug 08 07:25:14 vm7 corosync[21754]:  [QB    ] withdrawing server sockets
Aug 08 07:25:14 vm7 corosync[21754]:  [SERV  ] Service engine unloaded: corosync cluster quorum service v0.1
Aug 08 07:25:14 vm7 corosync[21754]:  [SERV  ] Service engine unloaded: corosync profile loading service
Aug 08 07:25:14 vm7 corosync[21754]:  [MAIN  ] Corosync Cluster Engine exiting normally
Aug 08 07:25:15 vm7 corosync[28134]: Waiting for corosync services to unload:.[  OK  ]
Aug 08 07:25:15 vm7 systemd[1]: Stopped Corosync Cluster Engine.
-- Subject: Unit corosync.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit corosync.service has finished shutting down.
Aug 08 07:25:15 vm7 systemd[1]: Reloading.
Aug 08 07:25:15 vm7 systemd[1]: Reloading.
Aug 08 07:25:15 vm7 systemd[1]: Reloading.
Aug 08 07:25:15 vm7 systemd-logind[806]: Removed session 1266.
-- Subject: Session 1266 has been terminated
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: http://www.freedesktop.org/wiki/Software/systemd/multiseat
--
-- A session with the ID 1266 has been terminated.
Aug 08 07:25:15 vm7 systemd[1]: Removed slice User Slice of root.
-- Subject: Unit user-0.slice has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit user-0.slice has finished shutting down.
Aug 08 07:25:17 vm7 ntpd[21296]: Deleting interface #8 eth3, fe80::5054:ff:fec6:dc2f#123, interface stats: received=0, sent=0, dropped=0, active_time=1829 secs
Aug 08 07:25:17 vm7 ntpd[21296]: Deleting interface #6 eth3, 10.128.0.23#123, interface stats: received=0, sent=0, dropped=0, active_time=1829 secs
Aug 08 07:30:01 vm7 systemd[1]: Created slice User Slice of root.
-- Subject: Unit user-0.slice has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit user-0.slice has finished starting up.
--
-- The start-up result is done.
Aug 08 07:30:01 vm7 systemd[1]: Started Session 1273 of user root.
-- Subject: Unit session-1273.scope has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit session-1273.scope has finished starting up.
--
-- The start-up result is done.
Aug 08 07:30:01 vm7 CROND[28515]: (root) CMD (/usr/lib64/sa/sa1 1 1)
Aug 08 07:30:01 vm7 systemd[1]: Removed slice User Slice of root.
-- Subject: Unit user-0.slice has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit user-0.slice has finished shutting down.
Aug 08 07:30:27 vm7 dhclient[1311]: DHCPREQUEST on eth0 to 192.168.121.1 port 67 (xid=0x59e11eee)
Aug 08 07:30:27 vm7 dhclient[1311]: DHCPACK from 192.168.121.1 (xid=0x59e11eee)
Aug 08 07:30:27 vm7 NetworkManager[1086]: <info>  [1565249427.3354] dhcp4 (eth0):   address 192.168.121.84
Aug 08 07:30:27 vm7 NetworkManager[1086]: <info>  [1565249427.3354] dhcp4 (eth0):   plen 24 (255.255.255.0)
Aug 08 07:30:27 vm7 NetworkManager[1086]: <info>  [1565249427.3354] dhcp4 (eth0):   gateway 192.168.121.1
Aug 08 07:30:27 vm7 NetworkManager[1086]: <info>  [1565249427.3354] dhcp4 (eth0):   lease time 3600
Aug 08 07:30:27 vm7 NetworkManager[1086]: <info>  [1565249427.3354] dhcp4 (eth0):   hostname 'vm7'
Aug 08 07:30:27 vm7 NetworkManager[1086]: <info>  [1565249427.3354] dhcp4 (eth0):   nameserver '192.168.121.1'
Aug 08 07:30:27 vm7 NetworkManager[1086]: <info>  [1565249427.3355] dhcp4 (eth0):   domain name 'trevis.whamcloud.com'
Aug 08 07:30:27 vm7 NetworkManager[1086]: <info>  [1565249427.3355] dhcp4 (eth0): state changed bound -> bound
Aug 08 07:30:27 vm7 dbus[818]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service'
Aug 08 07:30:27 vm7 systemd[1]: Starting Network Manager Script Dispatcher Service...
-- Subject: Unit NetworkManager-dispatcher.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit NetworkManager-dispatcher.service has begun starting up.
Aug 08 07:30:27 vm7 dhclient[1311]: bound to 192.168.121.84 -- renewal in 1317 seconds.
Aug 08 07:30:27 vm7 dbus[818]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
Aug 08 07:30:27 vm7 systemd[1]: Started Network Manager Script Dispatcher Service.
-- Subject: Unit NetworkManager-dispatcher.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit NetworkManager-dispatcher.service has finished starting up.
--
-- The start-up result is done.
Aug 08 07:30:27 vm7 nm-dispatcher[28547]: req:1 'dhcp4-change' [eth0]: new request (3 scripts)
Aug 08 07:30:27 vm7 nm-dispatcher[28547]: req:1 'dhcp4-change' [eth0]: start running ordered scripts...
Aug 08 07:40:01 vm7 systemd[1]: Created slice User Slice of root.
-- Subject: Unit user-0.slice has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit user-0.slice has finished starting up.
--
-- The start-up result is done.
```

**Comment by jgrund** [comment]
@utopiabound Can you take a look at this one? Looks like the hang is due to the way HA is being cleared.

**Comment by jgrund** [comment]
Hitting this error on a patch based on #1144: https://build.whamcloud.com/job/integration-tests-shared-storage-configuration/arch=x86_64,distro=el7,label=IML/2519
