### ISSUE TITLE
Remove filesystem fails creating PurgeFilesystemStep

### ISSUE THREAD

**Issue by utopiabound** [whamcloud/integrated-manager-for-lustre#1201]
**Describe the bug**
Removing a filesystem fails on last step while trying to build `PurgeFilesystemStep`

**Log of Traceback**
job_scheduler.log:
```
2019-09-06 15:41:09,759: ERROR/job_scheduler] Job 193: exception in get_steps: Traceback (most recent call last):
  File "/usr/share/chroma-manager/chroma_core/services/job_scheduler/job_scheduler.py", line 562, in _check_jobs
    job.steps = job.get_steps()
  File "/usr/share/chroma-manager/chroma_core/models/filesystem.py", line 231, in get_steps
    "mgs_device_type": mgs_target.active_mount.volume_node.volume.storage_resource.to_resource_class().device_type(),
AttributeError: 'NoneType' object has no attribute 'to_resource_class'
```
Loading IML then fails with the following in
http.log:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tastypie/resources.py", line 202, in wrapper
    response = callback(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tastypie/resources.py", line 433, in dispatch_list
    return self.dispatch('list', request, **kwargs)
  File "/usr/lib/python2.7/site-packages/tastypie/resources.py", line 465, in dispatch
    response = method(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/tastypie/resources.py", line 1287, in get_list
    objects = self.obj_get_list(bundle=base_bundle, **self.remove_api_resource_names(kwargs))
  File "/usr/share/chroma-manager/chroma_api/validation_utils.py", line 32, in _validate
    return fn(self, bundle, **kwargs)
  File "/usr/share/chroma-manager/chroma_api/action.py", line 123, in obj_get_list
    return self.get_object_list(bundle.request)
  File "/usr/share/chroma-manager/chroma_api/action.py", line 103, in get_object_list
    computed_transitions = JobSchedulerClient.available_transitions(ids)
  File "/usr/share/chroma-manager/chroma_core/services/job_scheduler/job_scheduler_client.py", line 97, in available_transitions
    return JobSchedulerRpc().available_transitions(object_list)
  File "/usr/share/chroma-manager/chroma_core/services/rpc.py", line 575, in <lambda>
    return lambda *args, **kwargs: self._call(name, *args, **kwargs)
  File "/usr/share/chroma-manager/chroma_core/services/rpc.py", line 591, in _call
    result = rpc_client.call(request, rpc_timeout)
  File "/usr/share/chroma-manager/chroma_core/services/rpc.py", line 436, in call
    raise RpcTimeout()
RpcTimeout
```

### Versions
IML: python2-iml-manager-5.0.1-1.1567086949.el7.noarch
CentOS 7.6

**Comment by utopiabound** [comment]
One of the oddities in my setup is that the filesystem I was deleting was mixed backend.
Specifically:
MGS: ZFS
MDT: ldiskfs
OSTs: ZFS

**Comment by jgrund** [comment]
If I had to guess I think that both the correct Volume / VolumeNode exist but the linkage between them is incorrect.

**Comment by utopiabound** [comment]
Sosreport taken after trying to remove filesystem named `fs10`
[sosreport-ieel-mgr1-IML-1201-2019-09-09-baglwqr.tar.gz](https://github.com/whamcloud/integrated-manager-for-lustre/files/3591312/sosreport-ieel-mgr1-IML-1201-2019-09-09-baglwqr.tar.gz)

**Comment by utopiabound** [comment]
This was due to a bug in iml-agent I was testing
