### ISSUE TITLE
Tests in tests/unit/services/job_scheduler/host/test_host.py are failing on master

### ISSUE THREAD

**Issue by mkpankov** [whamcloud/integrated-manager-for-lustre#1425]
Setup environment as described here
https://whamcloud.github.io/Online-Help/docs/Contributor_Docs/cd_integrated-manager-for-lustre_Unit_Testing.html

Run the tests
```
root@21f9d888be85:~/iml# python -W always manage.py test tests/unit/services/job_scheduler/host/test_host.py
/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
nosetests tests/unit/services/job_scheduler/host/test_host.py --verbosity=1
nose.plugins.ipdbplugin: WARNING: Autocomplete will not work with stdout capture on. Use --nocapture to have the ipdb shell working properly.
Creating test database for alias 'default'...
Creating groups...
***
***
***
*** SECURITY WARNING: You are running in DEBUG mode and default users have been created
***
***
***

Loaded 13 default power device types.
...EEEEEEEE
======================================================================
ERROR: test_relearn_add (test_host.TestNidChange)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/iml/tests/unit/services/job_scheduler/host/test_host.py", line 56, in test_relearn_add
    self.attempt_nid_change([Nid.Nid("192.168.0.1", "tcp", 0), Nid.Nid("192.168.0.2", "tcp", 0)])
  File "/root/iml/tests/unit/services/job_scheduler/host/test_host.py", line 48, in attempt_nid_change
    self.assertNidsCorrect(host)
  File "/root/iml/tests/unit/services/job_scheduler/host/test_host.py", line 25, in assertNidsCorrect
    [{"class_name": "UpdateDevicesJob", "args": {"hosts": [api.get_resource_uri(host)]}}], "Test update of nids"
  File "/root/iml/chroma_core/services/job_scheduler/job_scheduler_client.py", line 73, in command_run_jobs
    return JobSchedulerRpc().run_jobs(job_dicts, message)
  File "/root/iml/chroma_core/services/rpc.py", line 575, in <lambda>
    return lambda *args, **kwargs: self._call(name, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mock.py", line 955, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mock.py", line 1018, in _mock_call
    ret_val = effect(*args, **kwargs)
  File "/root/iml/tests/unit/services/job_scheduler/job_test_case.py", line 142, in rpc_local
    retval = json.loads(json.dumps(getattr(test_daemon, fn_name)(*args, **kwargs)))
  File "/root/iml/chroma_core/services/job_scheduler/job_scheduler.py", line 893, in run_jobs
    result = self.CommandPlan.command_run_jobs(job_dicts, message)
  File "/root/iml/chroma_core/services/job_scheduler/command_plan.py", line 501, in command_run_jobs
    job_instance = job_klass(**job["args"])
  File "/root/iml/chroma_core/models/host.py", line 72, in __init__
    super(HostListMixin, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 573, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'hosts' is an invalid keyword argument for this function
-------------------- >> begin captured logging << --------------------
storage_plugin: WARNING: Reloading module linux (okay if testing)
storage_plugin: WARNING: Double load of linux (okay if testing)
storage_plugin: WARNING: Reloading module linux_network (okay if testing)
storage_plugin: WARNING: Double load of linux_network (okay if testing)
chroma_core.lib.cache: INFO: clear
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_relearn_change (test_host.TestNidChange)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/iml/tests/unit/services/job_scheduler/host/test_host.py", line 53, in test_relearn_change
    self.attempt_nid_change([Nid.Nid("192.168.0.2", "tcp", 0)])
  File "/root/iml/tests/unit/services/job_scheduler/host/test_host.py", line 48, in attempt_nid_change
    self.assertNidsCorrect(host)
  File "/root/iml/tests/unit/services/job_scheduler/host/test_host.py", line 25, in assertNidsCorrect
    [{"class_name": "UpdateDevicesJob", "args": {"hosts": [api.get_resource_uri(host)]}}], "Test update of nids"
  File "/root/iml/chroma_core/services/job_scheduler/job_scheduler_client.py", line 73, in command_run_jobs
    return JobSchedulerRpc().run_jobs(job_dicts, message)
  File "/root/iml/chroma_core/services/rpc.py", line 575, in <lambda>
    return lambda *args, **kwargs: self._call(name, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mock.py", line 955, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mock.py", line 1018, in _mock_call
    ret_val = effect(*args, **kwargs)
  File "/root/iml/tests/unit/services/job_scheduler/job_test_case.py", line 142, in rpc_local
    retval = json.loads(json.dumps(getattr(test_daemon, fn_name)(*args, **kwargs)))
  File "/root/iml/chroma_core/services/job_scheduler/job_scheduler.py", line 893, in run_jobs
    result = self.CommandPlan.command_run_jobs(job_dicts, message)
  File "/root/iml/chroma_core/services/job_scheduler/command_plan.py", line 501, in command_run_jobs
    job_instance = job_klass(**job["args"])
  File "/root/iml/chroma_core/models/host.py", line 72, in __init__
    super(HostListMixin, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 573, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'hosts' is an invalid keyword argument for this function
-------------------- >> begin captured logging << --------------------
storage_plugin: WARNING: Reloading module linux (okay if testing)
storage_plugin: WARNING: Double load of linux (okay if testing)
storage_plugin: WARNING: Reloading module linux_network (okay if testing)
storage_plugin: WARNING: Double load of linux_network (okay if testing)
chroma_core.lib.cache: INFO: clear
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_relearn_remove (test_host.TestNidChange)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/iml/tests/unit/services/job_scheduler/host/test_host.py", line 59, in test_relearn_remove
    self.attempt_nid_change([])
  File "/root/iml/tests/unit/services/job_scheduler/host/test_host.py", line 48, in attempt_nid_change
    self.assertNidsCorrect(host)
  File "/root/iml/tests/unit/services/job_scheduler/host/test_host.py", line 25, in assertNidsCorrect
    [{"class_name": "UpdateDevicesJob", "args": {"hosts": [api.get_resource_uri(host)]}}], "Test update of nids"
  File "/root/iml/chroma_core/services/job_scheduler/job_scheduler_client.py", line 73, in command_run_jobs
    return JobSchedulerRpc().run_jobs(job_dicts, message)
  File "/root/iml/chroma_core/services/rpc.py", line 575, in <lambda>
    return lambda *args, **kwargs: self._call(name, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mock.py", line 955, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mock.py", line 1018, in _mock_call
    ret_val = effect(*args, **kwargs)
  File "/root/iml/tests/unit/services/job_scheduler/job_test_case.py", line 142, in rpc_local
    retval = json.loads(json.dumps(getattr(test_daemon, fn_name)(*args, **kwargs)))
  File "/root/iml/chroma_core/services/job_scheduler/job_scheduler.py", line 893, in run_jobs
    result = self.CommandPlan.command_run_jobs(job_dicts, message)
  File "/root/iml/chroma_core/services/job_scheduler/command_plan.py", line 501, in command_run_jobs
    job_instance = job_klass(**job["args"])
  File "/root/iml/chroma_core/models/host.py", line 72, in __init__
    super(HostListMixin, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 573, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'hosts' is an invalid keyword argument for this function
-------------------- >> begin captured logging << --------------------
storage_plugin: WARNING: Reloading module linux (okay if testing)
storage_plugin: WARNING: Double load of linux (okay if testing)
storage_plugin: WARNING: Reloading module linux_network (okay if testing)
storage_plugin: WARNING: Double load of linux_network (okay if testing)
chroma_core.lib.cache: INFO: clear
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_mgs_nid_change (test_host.TestUpdateNids)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/iml/tests/unit/services/job_scheduler/host/test_host.py", line 97, in test_mgs_nid_change
    self.mdt, mdt_tms = ManagedMdt.create_for_volume(synthetic_volume_full(mds).id, filesystem=self.fs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/root/iml/chroma_core/models/target.py", line 354, in create_for_volume
    filesystem = ObjectCache.get_by_id(type(target.filesystem), target.filesystem.id)
  File "/root/iml/chroma_core/lib/cache.py", line 71, in get_by_id
    raise klass.DoesNotExist()
DoesNotExist: 
-------------------- >> begin captured logging << --------------------
storage_plugin: WARNING: Reloading module linux (okay if testing)
storage_plugin: WARNING: Double load of linux (okay if testing)
storage_plugin: WARNING: Reloading module linux_network (okay if testing)
storage_plugin: WARNING: Double load of linux_network (okay if testing)
chroma_core.lib.cache: INFO: clear
storage_plugin: INFO: StorageResourceRecord created 6
storage_plugin: INFO: StorageResourceRecord created 7
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 7 tests in 2.975s

FAILED (errors=4)
Destroying test database for alias 'default'...
root@21f9d888be85:~/iml# 

```

**Comment by mkpankov** [comment]
I'm going to look into `test_mgs_nid_change` at least as I need it for #1416

**Comment by jgrund** [comment]
hrrm, there must be a step missing in the doc then, as these are passing on master:

https://travis-ci.com/whamcloud/integrated-manager-for-lustre/jobs/269612015.

@mkpankov can you see what's different between the travis config and the docs and update if necessary?

https://github.com/whamcloud/integrated-manager-for-lustre/blob/master/.travis.yml

**Comment by jgrund** [comment]
Ah, the doc is only specifying unit tests. Should probably also document service tests:

https://github.com/whamcloud/integrated-manager-for-lustre/blob/8be4d0fda5f838d263791ac372a6f28f84655410/.travis.yml#L47-L53

**Comment by mkpankov** [comment]
These are still unit tests, not service ones. They are run in `Unit tests` stage on Travis.

I think there's dependency on other tests.

When running locally entire suite (`tests/unit`, as in Travis), I get 

```
FAILED (SKIP=3, errors=4)
```

of which errors are `test_version`, `test_cancel`, `test_get_data` and `test_send_action`, and errors seem unrelated to my initial problem.

When running just a single file `tests/unit/services/job_scheduler/host/test_host.py`, I get the problem with log in the issue description.

Will now take a look at fixture.

**Comment by mkpankov** [comment]
Apparently it works well when running `tests/unit/services` and `tests/unit/job_scheduler`, but below that, there are interdependencies between tests.

**Comment by mkpankov** [comment]
It turns out problem isn't interdependencies, it's just that these tests are disabled.

`tests/unit/services/job_scheduler/host/__init__.py` was missing, so both files `tests/unit/services/job_scheduler/host/{test_host_contact,test_host}.py` were disabled.

How to check: run 
```
python -W always manage.py test --collect-only --with-xunit --xunit-file xunit.xml
```

then search for `test_mgs_nid_change` in `xunit.xml`.

I'm now enabling these tests back but I think I'll need help fixing them.

**Comment by mkpankov** [comment]
Enabling in https://github.com/whamcloud/integrated-manager-for-lustre/pull/1431

**Comment by jgrund** [comment]
Good catch.
