### ISSUE TITLE
_get_resource_locations parse Error

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#1514]
I'm seeing the following traceback multiple times within SSI testing:

```
[22/Jan/2020:07:52:31] daemon ERROR Error in plugin lustre: Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/chroma_agent/agent_client.py", line 510, in poll
    data = session.poll()

  File "/usr/lib/python2.7/site-packages/chroma_agent/agent_client.py", line 260, in poll
    return self._plugin.update_session()

  File "/usr/lib/python2.7/site-packages/chroma_agent/device_plugins/lustre.py", line 115, in update_session
    return self._delta_result(self._scan(), self.delta_fields)

  File "/usr/lib/python2.7/site-packages/chroma_agent/device_plugins/lustre.py", line 91, in _scan
    resource_locations = manage_targets.get_resource_locations()

  File "/usr/lib/python2.7/site-packages/chroma_agent/action_plugins/manage_targets.py", line 89, in get_resource_locations
    return _get_resource_locations(result.stdout)

  File "/usr/lib/python2.7/site-packages/chroma_agent/action_plugins/manage_targets.py", line 48, in _get_resource_locations
    dom = ET.fromstring(xml)

  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)

  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)

  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err

ParseError: syntax error: line 1, column 0
```

**Comment by utopiabound** [comment]
```
[22/Jan/2020:11:16:44] daemon WARNING rc=107 running '['crm_mon', '--one-shot', '--as-xml']': '
Error: cluster is not available on this node
' ''
[22/Jan/2020:11:16:44] daemon INFO Session.send_message corosync/eab1527b-3306-43f8-8a13-751695d1eaaf
[22/Jan/2020:11:16:44] daemon DEBUG HttpWriter got message from primary queue
[22/Jan/2020:11:16:44] daemon DEBUG HttpWriter sending 1 messages
[22/Jan/2020:11:16:45] daemon ERROR Error in plugin lustre: Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/chroma_agent/agent_client.py", line 510, in poll
    data = session.poll()

  File "/usr/lib/python2.7/site-packages/chroma_agent/agent_client.py", line 260, in poll
    return self._plugin.update_session()

  File "/usr/lib/python2.7/site-packages/chroma_agent/device_plugins/lustre.py", line 115, in update_session
    return self._delta_result(self._scan(), self.delta_fields)

  File "/usr/lib/python2.7/site-packages/chroma_agent/device_plugins/lustre.py", line 91, in _scan
    resource_locations = manage_targets.get_resource_locations()

  File "/usr/lib/python2.7/site-packages/chroma_agent/action_plugins/manage_targets.py", line 89, in get_resource_locations
    return _get_resource_locations(result.stdout)

  File "/usr/lib/python2.7/site-packages/chroma_agent/action_plugins/manage_targets.py", line 48, in _get_resource_locations
    dom = ET.fromstring(xml)

  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)

  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)

  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err

ParseError: syntax error: line 1, column 0
```

If `result.stdout` is empty, you'd get that same ParseError.
