### ISSUE TITLE
SSI: test_writeconf.testUpdateNids failing

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#1523]
There appears to be a consistent SSI failure in `test_writeconf.testUpdateNids`.

Ref: https://build.whamcloud.com/job/integration-tests-shared-storage-configuration/3828

Traceback:

```
2020-01-24 05:27:21,029 - test - ERROR - Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_writeconf.py", line 59, in testUpdateNids
    self._exercise_simple(self.filesystem_id)
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_writeconf.py", line 9, in _exercise_simple
    self.remote_operations.mount_filesystem(client, filesystem)
  File "/usr/share/chroma-manager/tests/integration/core/remote_operations.py", line 398, in mount_filesystem
    self._ssh_address(client_address, filesystem["mount_command"])
  File "/usr/share/chroma-manager/tests/integration/core/remote_operations.py", line 228, in _ssh_address
    stdout = channel.makefile("rb").read()
  File "/usr/lib/python2.7/site-packages/paramiko/file.py", line 192, in read
    new_data = self._read(self._DEFAULT_BUFSIZE)
  File "/usr/lib/python2.7/site-packages/paramiko/channel.py", line 1292, in _read
    return self.channel.recv(size)
  File "/usr/lib/python2.7/site-packages/paramiko/channel.py", line 667, in recv
    raise socket.timeout()
timeout:
```

**Comment by jgrund** [comment]
It appears the issue is that replace_nids is receiving the mgs nids for each target. This will need to be updated to return the current nid for each target being replaced.
