### ISSUE TITLE
AssertionError: bash: zfs: command not found

### ISSUE THREAD

**Issue by brianjmurrell** [whamcloud/integrated-manager-for-lustre#166]
If one tries to run a single test, in this case it was _test_same_name_ the `zfs` command is not available during the pre-test setup:

```
Running tests in tests/integration/shared_storage_configuration/test_filesystem_same_name.py:TestFilesystemSameNameHYD832.test_same_name
----------------------------------------------------------------------
test_same_name (tests.integration.shared_storage_configuration.test_filesystem_same_name.TestFilesystemSameNameHYD832) ... ERROR
ERROR
Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 163, in setUp
    True)
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 958, in cleanup_zfs_pools
    'listing zfs devices')[0].split()
  File "/usr/share/chroma-manager/tests/integration/core/utility_testcase.py", line 71, in execute_commands
    result = self.remote_command(target, command, expected_return_code=expected_return_code)
  File "/usr/share/chroma-manager/tests/integration/core/utility_testcase.py", line 114, in remote_command
    self.assertEqual(exit_status, expected_return_code, stderr)
AssertionError: bash: zfs: command not found
```

The test code should either install any tools that it needs or it should handle missing tools gracefully.

**Comment by jgrund** [comment]
No longer appears to be issue.
