### ISSUE TITLE
iml-devices panics on initial detection of devices

### ISSUE THREAD

**Issue by mkpankov** [whamcloud/integrated-manager-for-lustre#1759]
I've seen it twice now
```
Apr 02 11:00:23 adm.local iml-devices[5891]: Apr 02 11:00:23.338  INFO iml_devices::build_new_state: Local virtual device host: (zpool_11170787388868102037, mds1.local, true, {"mdt0"})
Apr 02 11:00:23 adm.local iml-devices[5891]: thread 'main' panicked at 'no entry found for key', /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/collections/btree/map.rs:1891:9
Apr 02 11:00:23 adm.local iml-devices[5891]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Apr 02 11:00:23 adm.local systemd[1]: Unit iml-devices.service entered failed state.
Apr 02 11:00:23 adm.local systemd[1]: iml-devices.service failed.
```
and
```
Apr 02 11:02:28 adm.local iml-devices[6565]: Apr 02 11:02:28.240  INFO iml_devices::build_new_state: Local virtual device host: (zpool_11170787388868102037, mds1.local, true, {"mdt0"})
Apr 02 11:02:28 adm.local iml-devices[6565]: thread 'main' panicked at 'no entry found for key', /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/collections/btree/map.rs:1891:9
Apr 02 11:02:28 adm.local iml-devices[6565]: stack backtrace:
Apr 02 11:02:28 adm.local iml-devices[6565]: 0: <unknown>
Apr 02 11:02:28 adm.local iml-devices[6565]: 1: core::fmt::write
Apr 02 11:02:28 adm.local iml-devices[6565]: 2: <unknown>
Apr 02 11:02:28 adm.local iml-devices[6565]: 3: <unknown>
Apr 02 11:02:28 adm.local iml-devices[6565]: 4: <unknown>
Apr 02 11:02:28 adm.local iml-devices[6565]: 5: std::panicking::rust_panic_with_hook
Apr 02 11:02:28 adm.local iml-devices[6565]: 6: rust_begin_unwind
Apr 02 11:02:28 adm.local iml-devices[6565]: 7: core::panicking::panic_fmt
Apr 02 11:02:28 adm.local iml-devices[6565]: 8: core::option::expect_failed
Apr 02 11:02:28 adm.local iml-devices[6565]: 9: <iml_devices::breadth_first_parent_iterator::BreadthFirstParentIterator as core::iter::traits::iterator::Iterator>::next
Apr 02 11:02:28 adm.local iml-devices[6565]: 10: <unknown>
Apr 02 11:02:28 adm.local iml-devices[6565]: 11: <unknown>
Apr 02 11:02:28 adm.local iml-devices[6565]: 12: iml_devices::virtual_device::virtual_device_changes
Apr 02 11:02:28 adm.local iml-devices[6565]: 13: <unknown>
Apr 02 11:02:28 adm.local iml-devices[6565]: 14: <unknown>
Apr 02 11:02:28 adm.local iml-devices[6565]: 15: <unknown>
Apr 02 11:02:28 adm.local iml-devices[6565]: 16: <unknown>
Apr 02 11:02:28 adm.local iml-devices[6565]: 17: <unknown>
Apr 02 11:02:28 adm.local iml-devices[6565]: 18: <unknown>
Apr 02 11:02:28 adm.local iml-devices[6565]: 19: <unknown>
Apr 02 11:02:28 adm.local iml-devices[6565]: 20: <unknown>
Apr 02 11:02:28 adm.local iml-devices[6565]: 21: __rust_maybe_catch_panic
Apr 02 11:02:28 adm.local iml-devices[6565]: 22: std::rt::lang_start_internal
Apr 02 11:02:28 adm.local iml-devices[6565]: 23: <unknown>
Apr 02 11:02:28 adm.local iml-devices[6565]: 24: __libc_start_main
Apr 02 11:02:28 adm.local iml-devices[6565]: 25: <unknown>
Apr 02 11:02:28 adm.local iml-devices[6565]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Apr 02 11:02:28 adm.local systemd[1]: Unit iml-devices.service entered failed state.
```

I know why this happens exactly, just need to identify the reason. Either:
1. I'm merging state incorrectly
1. Device Scanner sends a tree that doesn't have all the parents linked by childs

First reason is actually more probable.

**Comment by jgrund** [comment]
Looks like this was happening on an in-flight patch.
