### ISSUE TITLE
Cannot grow ostpool twice

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#1852]
Consider the following:

```sh
iml filesystem pool create fs fast
iml filesystem pool grow fs fast fs-OST0000
iml filesystem pool grow fs fast fs-OST0001
```

The last call fails with:

```
Growing ost pool...
[1/1]   ✗ Updating OST Pool errored
✗ The following commands have failed:
Updating OST Pool
```

relevant traceback from job_scheduler:

```
[2020-05-01 14:54:01,733: ERROR/rpc] RunOneRpc: exception calling create_ostpool: Traceback (most recent call last):

  File "/usr/share/chroma-manager/chroma_core/services/rpc.py", line 107, in run
    "result": self.rpc._local_call(self.body["method"], *self.body["args"], **self.body["kwargs"]),

  File "/usr/share/chroma-manager/chroma_core/services/rpc.py", line 622, in _local_call
    return fn(*args, **kwargs)

  File "/usr/share/chroma-manager/chroma_core/services/job_scheduler/job_scheduler.py", line 1146, in create_ostpool
    ostpool = OstPool.objects.create(**pool)

  File "/usr/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)

  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)

  File "/usr/share/chroma-manager/polymorphic/models.py", line 50, in save
    base_save()

  File "/usr/share/chroma-manager/polymorphic/models.py", line 28, in _nested_commit_on_success
    return func(*args, **kwds)

  File "/usr/share/chroma-manager/polymorphic/models.py", line 48, in base_save
    models.Model.save(self, *args, **kwargs)

  File "/usr/lib/python2.7/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)

  File "/usr/lib/python2.7/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)

  File "/usr/lib/python2.7/site-packages/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)

  File "/usr/lib/python2.7/site-packages/django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)

  File "/usr/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)

  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 1079, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)

  File "/usr/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1112, in execute_sql
    cursor.execute(sql, params)

  File "/usr/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)

  File "/usr/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)

  File "/usr/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)

IntegrityError: duplicate key value violates unique constraint "chroma_core_ostpool_name_filesystem_id_not_d_d2783eca_uniq"
DETAIL:  Key (name, filesystem_id, not_deleted)=(fast, 1, t) already exists.
```

**Comment by ip1981** [comment]
From the agent node (mds1 for `fs`):

```
jul 10 15:12:05 mds1.local iml-agent-daemon[17092]: Jul 10 15:12:05.297 DEBUG iml_cmd: Running cmd: Command { std: "/usr/sbin/lctl" "pool_new" "fs.fast", kill_on_drop: false }
jul 10 15:12:21 mds1.local iml-agent-daemon[17092]: Jul 10 15:12:21.673 DEBUG iml_cmd: Running cmd: Command { std: "/usr/sbin/lctl" "pool_add" "fs.fast" "fs-OST0000", kill_on_drop: false }
jul 10 15:12:33 mds1.local iml-agent-daemon[17092]: Jul 10 15:12:33.391 DEBUG iml_agent::reader: --> Delivery from manager Data { fqdn: Fqdn("mds1.local"), plugin: PluginName("action_runner"), session_id: Id("0d29ecdb-4433-4a8f-b177-8ea03bbfa165"), body: Object({"type": String("ACTION_START"), "action": String("ostpool_remove"), "args": Object({"ost": String("fs-OST0000"), "name": String("fast"), "filesystem": String("fs")}), "id": String("ba3455c5-18d5-4e57-9d38-56134719d92d")}) }
jul 10 15:12:33 mds1.local iml-agent-daemon[17092]: Jul 10 15:12:33.391 DEBUG iml_agent::reader: --> Delivery from manager Data { fqdn: Fqdn("mds1.local"), plugin: PluginName("action_runner"), session_id: Id("0d29ecdb-4433-4a8f-b177-8ea03bbfa165"), body: Object({"type": String("ACTION_START"), "action": String("ostpool_add"), "args": Object({"ost": String("fs-OST0001"), "name": String("fast"), "filesystem": String("fs")}), "id": String("7e88f90c-37fb-4c09-b2ad-0e84433b1cc2")}) }
jul 10 15:12:33 mds1.local iml-agent-daemon[17092]: Jul 10 15:12:33.391 DEBUG iml_agent::reader: --> Delivery from manager Data { fqdn: Fqdn("mds1.local"), plugin: PluginName("action_runner"), session_id: Id("0d29ecdb-4433-4a8f-b177-8ea03bbfa165"), body: Object({"type": String("ACTION_START"), "action": String("ostpool_add"), "args": Object({"ost": String("fs-OST0000"), "name": String("fast"), "filesystem": String("fs")}), "id": String("267538fe-4713-4ed6-8e40-bc04ec9c43ec")}) }
jul 10 15:12:33 mds1.local iml-agent-daemon[17092]: Jul 10 15:12:33.391 DEBUG iml_agent::http_comms::agent_client: Sending get [("server_boot_time", "2020-07-09T11:10:31.000000+00:00Z"), ("client_start_time", "2020-07-10T15:02:53.808536+00:00Z")]
jul 10 15:12:33 mds1.local iml-agent-daemon[17092]: Jul 10 15:12:33.391 DEBUG iml_cmd: Running cmd: Command { std: "/usr/sbin/lctl" "pool_remove" "fs.fast" "fs-OST0000", kill_on_drop: false }
jul 10 15:12:33 mds1.local iml-agent-daemon[17092]: Jul 10 15:12:33.391 DEBUG iml_cmd: Running cmd: Command { std: "/usr/sbin/lctl" "pool_add" "fs.fast" "fs-OST0001", kill_on_drop: false }
jul 10 15:12:33 mds1.local iml-agent-daemon[17092]: Jul 10 15:12:33.396 DEBUG iml_cmd: Running cmd: Command { std: "/usr/sbin/lctl" "pool_add" "fs.fast" "fs-OST0000", kill_on_drop: false }
jul 10 15:12:33 mds1.local iml-agent-daemon[17092]: Jul 10 15:12:33.403 DEBUG iml_agent::http_comms::agent_client: Sending session data for PluginName("action_runner")(Id("0d29ecdb-4433-4a8f-b177-8ea03bbfa165")): Ok(Object({"id": String("267538fe-4713-4ed6-8e40-bc04ec9c43ec"), "result": Object({"Err": String("exit code: 17, stdout: , stderr: OST fs-OST0000_UUID is already in pool fs.fast\npool_add: File exists\n")})}))
```

Manual:
```
[root@mds1 ~]# "/usr/sbin/lctl" "pool_new" "fs.fast"
Pool fs.fast created
[root@mds1 ~]# "/usr/sbin/lctl" "pool_add" "fs.fast" "fs-OST0000"
OST fs-OST0000_UUID added to pool fs.fast
[root@mds1 ~]# "/usr/sbin/lctl" "pool_remove" "fs.fast" "fs-OST0000"
OST fs-OST0000_UUID removed from pool fs.fast
[root@mds1 ~]# "/usr/sbin/lctl" "pool_add" "fs.fast" "fs-OST0001"
OST fs-OST0001_UUID added to pool fs.fast
[root@mds1 ~]# "/usr/sbin/lctl" "pool_add" "fs.fast" "fs-OST0000"
OST fs-OST0000_UUID added to pool fs.fast

```
