### ISSUE TITLE
Filesystem detection sometimes fails

### ISSUE THREAD

**Issue by johnsonw** [whamcloud/integrated-manager-for-lustre#1895]
Sometimes the integration tests fails when detecting the filesystem. This is most likely to occur if IML hasn't finished propagating all device information before the filesystem detection command is run.

**Comment by jgrund** [comment]
I think I've hit this in https://build.whamcloud.com/view/IML/job/manager-for-lustre/499/ . Relevant  bit of traceback:

```
[2020-05-13 19:03:42,056: ERROR/job_scheduler] Job 29 step 1 encountered an error: 'lvs':Traceback (most recent call last):
  File "/usr/share/chroma-manager/chroma_core/services/job_scheduler/job_scheduler.py", line 346, in _run
    result = step.run(args)
  File "/usr/share/chroma-manager/chroma_core/models/host.py", line 1016, in run
    DetectScan(self).run(host_data)
  File "/usr/share/chroma-manager/chroma_core/lib/detection.py", line 72, in run
    self.learn_failed_lustre_tunefs_secondary_lvm_mounts()
  File "/usr/share/chroma-manager/chroma_core/lib/detection.py", line 370, in learn_failed_lustre_tunefs_secondary_lvm_mounts
    for vgname in devices["lvs"]:
KeyError: 'lvs'
```

**Comment by jgrund** [comment]
One of a few issues here is we assume that `get_devices` will always return a dict with a `"lvs"` key on it. This is not the case if there is no data yet for a host  in the device service.

Instead of blowing up with a `KeyError` we should report the fact that no info was found for the given host.

The second issue is we are scanning all nodes for filesystems, including worker / client nodes. For detect filesystems, we should filter out workers.

The third issue is we should start the device service by loading whatever we have from the db into cache. This would help alleviate the gap between restarting the manager and seeing device data, especially if it was seen before.
