### ISSUE TITLE
Running chroma-config setup on already setup DB raises Django exception

### ISSUE THREAD

**Issue by mkpankov** [whamcloud/integrated-manager-for-lustre#1923]
```
    adm: ++ chroma-config setup admin lustre localhost --no-dbspace-check
    adm: Starting setup...
    adm: Clearing all sessions...
    adm: Starting InfluxDB...
    adm: Creating InfluxDB database...
    adm: Postgres already accessible
    adm: Creating database tables...
    adm: Traceback (most recent call last):
    adm:   File "/bin/chroma-config", line 10, in <module>
    adm:     load_entry_point('iml-manager==6.0.0', 'console_scripts', 'chroma-config')()
    adm:   File "/usr/share/chroma-manager/chroma_core/lib/service_config.py", line 1054, in chroma_config
    adm:     errors = service_config.setup(username, password, ntpserver, check_db_space)
    adm:   File "/usr/share/chroma-manager/chroma_core/lib/service_config.py", line 794, in setup
    adm:     error = self._setup_database(check_db_space)
    adm:   File "/usr/share/chroma-manager/chroma_core/lib/service_config.py", line 621, in _setup_database
    adm:     self._syncdb()
    adm:   File "/usr/share/chroma-manager/chroma_core/lib/service_config.py", line 596, in _syncdb
    adm:     ManagementUtility(args).execute()
    adm:   File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    adm:     self.fetch_command(subcommand).run_from_argv(self.argv)
    adm:   File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    adm:     self.execute(*args, **cmd_options)
    adm:   File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    adm:     output = self.handle(*args, **options)
    adm:   File "/usr/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    adm:     fake_initial=fake_initial,
    adm:   File "/usr/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    adm:     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
    adm:   File "/usr/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    adm:     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
    adm:   File "/usr/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    adm:     state = migration.apply(state, schema_editor)
    adm:   File "/usr/lib/python2.7/site-packages/django/db/migrations/migration.py", line 129, in apply
    adm:     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
    adm:   File "/usr/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 108, in database_forwards
    adm:     self._run_sql(schema_editor, self.sql)
    adm:   File "/usr/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 133, in _run_sql
    adm:     schema_editor.execute(statement, params=None)
    adm:   File "/usr/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 136, in execute
    adm:     cursor.execute(sql, params)
    adm:   File "/usr/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    adm:     return self.cursor.execute(sql, params)
    adm:   File "/usr/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    adm:     six.reraise(dj_exc_type, dj_exc_value, traceback)
    adm:   File "/usr/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    adm:     return self.cursor.execute(sql)
    adm: django.db.utils.ProgrammingError: type "lustre_fid" already exists
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

Dropping the database works around this issue.

**Comment by utopiabound** [comment]
It shouldn't be trying to re-run the migration, should it?

**Comment by mkpankov** [comment]
I have to add this is not on master, will verify there once I have a chance.

**Comment by jgrund** [comment]
It shouldn't be, but all migrations should be idempotent anyway.

**Comment by jgrund** [comment]
https://github.com/whamcloud/integrated-manager-for-lustre/blob/f177904d216fbd8fe4483a2d5eb60440699a30bd/chroma_core/migrations/__init__.py#L75

Should be something like:

```sql
DO $$ BEGIN
    CREATE TYPE lustre_fid AS (seq bigint, oid integer, ver integer);
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;
```

Then if a user is somehow in a state where the migration is run again it will not cause a failure.

**Comment by mkpankov** [comment]
Will try the suggested fix.

**Comment by jgrund** [comment]
@mkpankov push a separate patch for it so it can land separately.

**Comment by mkpankov** [comment]
Sure
