### ISSUE TITLE
Influx can't be setup if its already setup

### ISSUE THREAD

**Issue by mkpankov** [whamcloud/integrated-manager-for-lustre#1950]
```
    adm: Creating InfluxDB database...
    adm: Traceback (most recent call last):
    adm:   File "/bin/chroma-config", line 10, in <module>
    adm:     load_entry_point('iml-manager==6.1.0', 'console_scripts', 'chroma-config')()
    adm:   File "/usr/share/chroma-manager/chroma_core/lib/service_config.py", line 1056, in chroma_config
    adm:     errors = service_config.setup(username, password, ntpserver, check_db_space)
    adm:   File "/usr/share/chroma-manager/chroma_core/lib/service_config.py", line 794, in setup
    adm:     self._setup_influxdb()
    adm:   File "/usr/share/chroma-manager/chroma_core/lib/service_config.py", line 372, in _setup_influxdb
    adm:     
    adm: settings.INFLUXDB_IML_STATS_DB, settings.INFLUXDB_IML_STATS_DB,
    adm:   File "/usr/share/chroma-manager/chroma_core/lib/util.py", line 192, in try_shell
    adm:     raise CommandError(cmdline, rc, out, err)
    adm: chroma_core.lib.util.CommandError
    adm: : 
    adm: Command failed: ['influx', '-database', 'iml_stats', '-execute', 'CREATE CONTINUOUS QUERY "downsample_means" ON "iml_stats" BEGIN SELECT mean(*) INTO "iml_stats"."long_term".:MEASUREMENT FROM "iml_stats"."autogen"."target","iml_stats"."autogen"."host","iml_stats"."autogen"."node" GROUP BY time(30m),* END; CREATE CONTINUOUS QUERY "downsample_lnet" ON "iml_stats" BEGIN SELECT (last("send_count") - first("send_count")) / count("send_count") AS "mean_diff_send", (last("recv_count") - first("recv_count")) / count("recv_count") AS "mean_diff_recv" INTO "iml_stats"."long_term"."lnet" FROM "lnet" WHERE "nid" != \'"0@lo"\' GROUP BY time(30m),"host","nid" END; CREATE CONTINUOUS QUERY "downsample_samples" ON "iml_stats" BEGIN SELECT (last("samples") - first("samples")) / count("samples") AS "mean_diff_samples" INTO "iml_stats"."long_term"."target" FROM "target" GROUP BY time(30m),* END; CREATE CONTINUOUS QUERY "downsample_sums" ON "iml_stats" BEGIN SELECT (last("sum") - first("sum")) / count("sum") AS "mean_diff_sum" INTO "iml_stats"."long_term"."target" FROM "target" WHERE "units"=\'"bytes"\' GROUP BY time(30m),* END']
    adm:     return code 1
    adm:     stdout: 
    adm: 
    adm: 
    adm: ERR: continuous query already exists
    adm: 
    adm:     stderr: continuous query already exists
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by jgrund** [comment]
The CQ needs to be dropped and re-added. @utopiabound Can you fix this?
