### ISSUE TITLE
IML bugreport Error when trying to create a filesystem from the GUI using a custom profile

### ISSUE THREAD

**Issue by gustavo4passos** [whamcloud/integrated-manager-for-lustre#2032]
**Describe the bug**
I'm unable to create a new file system from the UI using a custom server profile. The profile is very similar to the default "base_managed_rh7" profile, but with corosync and pacemaker disabled (the intention is to disable HA).  
Here's the profile:  
```json
{
  "ui_name": "Managed Storage Server, no HA",
  "managed": true,
  "worker": false,
  "name": "base_managed_rh7_no_ha",
  "initial_state": "managed",
  "ntp": true,
  "corosync": false,
  "corosync2": false,
  "pacemaker": false,
  "ui_description": "A storage server suitable for creating filesystem targets",
  "packages": [
    "python2-iml-agent-management",
    "kernel-devel-lustre",
    "lustre-ldiskfs-zfs"
  ],
  "repolist": [
    "base",
    "lustre-server"
  ],
  "validation": [
    {
      "description": "The profile is designed for version 7 of EL",
      "test": "distro_version < 8 and distro_version >= 7"
    }
  ]
}
```

**To Reproduce**
1. Go to the servers page.
2. Click on "Add More Servers", 
3. Add and configure three servers, using a custom profile (the profile is shown above)
4. Go to the file systems page, and click on create file system.
5. Click on "create file system".
6. Configure the file system according to the screenshot below.
7. Click on the "Create file system" button
8. See error shown on the screenshot below  

I'm listing some logs on the [logs section below](#logs).

**Expected behavior**

**Screenshots**
Here's my filesystem config:
![Settings](https://user-images.githubusercontent.com/30205936/86258589-5c374700-bb91-11ea-8a8f-2424b44e434c.PNG)
Here's the error I get in the browser:
![browser error](https://user-images.githubusercontent.com/30205936/86258632-69eccc80-bb91-11ea-9989-1aa9e6a29955.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version: 83.0.4103.116

### Version
What version of IML?
5.1.0
What Operating System?
RHEL
What Operating System version?
7.6

### Logs
(click to expand)
<details><summary>job_scheduler.log</summary>  

```  

[2020-07-01 11:17:25,418: INFO/job_scheduler] Job 237 completing (errored=False, cancelled=False)
[2020-07-01 11:17:25,554: INFO/job_scheduler] run_next: 1 runnable jobs of (1 pending, 0 tasked)
[2020-07-01 11:17:25,640: INFO/job_scheduler] Job 238: RunJobThread.run
[2020-07-01 11:17:25,641: INFO/job] invoke_agent on agent mgs-1 initialise_block_device_drivers {}
[2020-07-01 11:17:25,711: INFO/chroma_core.services.job_scheduler.agent_rpc] AgentRpcMessenger._complete: starting wait for rpc e15d23d4-9ff5-4cc6-a3ca-006cf2a20931
[2020-07-01 11:17:25,711: INFO/chroma_core.services.job_scheduler.agent_rpc] AgentRpcMessenger._complete: starting wait for rpc e15d23d4-9ff5-4cc6-a3ca-006cf2a20931
[2020-07-01 11:17:25,814: INFO/chroma_core.services.job_scheduler.agent_rpc] AgentRpcMessenger.on_rx: mgs-1/7437f3c9-1300-4135-ade3-d0ff83e036b1
[2020-07-01 11:17:25,814: INFO/chroma_core.services.job_scheduler.agent_rpc] AgentRpcMessenger.on_rx: mgs-1/7437f3c9-1300-4135-ade3-d0ff83e036b1
[2020-07-01 11:17:25,815: INFO/chroma_core.services.job_scheduler.agent_rpc] AgentRpcMessenger.on_rx: good session mgs-1/7437f3c9-1300-4135-ade3-d0ff83e036b1
[2020-07-01 11:17:25,815: INFO/chroma_core.services.job_scheduler.agent_rpc] AgentRpcMessenger.on_rx: good session mgs-1/7437f3c9-1300-4135-ade3-d0ff83e036b1
[2020-07-01 11:17:25,815: INFO/chroma_core.services.job_scheduler.agent_rpc] AgentRpcMessenger.on_rx: completing rpc e15d23d4-9ff5-4cc6-a3ca-006cf2a20931
[2020-07-01 11:17:25,815: INFO/chroma_core.services.job_scheduler.agent_rpc] AgentRpcMessenger.on_rx: completing rpc e15d23d4-9ff5-4cc6-a3ca-006cf2a20931
[2020-07-01 11:17:25,839: INFO/chroma_core.services.job_scheduler.agent_rpc] AgentRpcMessenger._complete: completed wait for rpc e15d23d4-9ff5-4cc6-a3ca-006cf2a20931
[2020-07-01 11:17:25,839: INFO/chroma_core.services.job_scheduler.agent_rpc] AgentRpcMessenger._complete: completed wait for rpc e15d23d4-9ff5-4cc6-a3ca-006cf2a20931
[2020-07-01 11:17:25,840: INFO/job_scheduler] Job 238 finished 1 steps successfully
[2020-07-01 11:17:25,881: INFO/job] StatefulObject.set_state mgs-1 unconfigured->managed (intentional=True) 140402806789904
[2020-07-01 11:17:25,885: INFO/job] Job 238: StateChangeJob complete, setting state managed on mgs-1
[2020-07-01 11:17:25,885: INFO/job] Job 238: not_deleted=True
[2020-07-01 11:17:25,885: INFO/job_scheduler] Job 238: complete_job: Updating cache
[2020-07-01 11:17:25,885: INFO/job] Job 238: StateChangeJob complete, setting state managed on mgs-1
[2020-07-01 11:17:25,885: INFO/job] Job 238: not_deleted=True
[2020-07-01 11:17:25,885: INFO/job_scheduler] Job 238: complete_job: Updating cache
[2020-07-01 11:17:25,885: INFO/job_scheduler] Job 238: locked_item 140402806789904 <class 'chroma_core.models.host.ManagedHost'> True True
[2020-07-01 11:17:25,888: INFO/job_scheduler] Job 238 completing (errored=False, cancelled=False)
[2020-07-01 11:17:26,185: INFO/job_scheduler] Replaying 2 buffered notifications for ManagedHost-12
[2020-07-01 11:17:26,216: INFO/job_scheduler] _notify: Updating .immutable_state of item 12 (mgs-1) from True to False
[2020-07-01 11:17:26,216: INFO/job_scheduler] _notify: Set immutable_state=False on mgs-1 (ManagedHost-12) and saved
[2020-07-01 11:17:26,230: INFO/job_scheduler] run_next: 0 runnable jobs of (0 pending, 0 tasked)
[2020-07-01 11:37:52,228: ERROR/rpc] RunOneRpc: exception calling create_filesystem: Traceback (most recent call last):

  File "/usr/share/chroma-manager/chroma_core/services/rpc.py", line 107, in run
    "result": self.rpc._local_call(self.body["method"], *self.body["args"], **self.body["kwargs"]),

  File "/usr/share/chroma-manager/chroma_core/services/rpc.py", line 622, in _local_call
    return fn(*args, **kwargs)

  File "/usr/share/chroma-manager/chroma_core/services/job_scheduler/job_scheduler.py", line 1213, in create_filesystem
    mgt_data["volume_id"], reformat=mgt_data.get("reformat", False), **_target_kwargs(mgt_data)

  File "/usr/share/chroma-manager/chroma_core/models/target.py", line 340, in create_for_volume
    stonith_not_enabled = (

AttributeError: 'NoneType' object has no attribute 'id'  

```
</details>

<details><summary>http.log</summary>  

```  
[2020-07-01 11:08:53,094: WARNING/chroma_core.services.http_agent.sessions] Destroying session mgs-1/linux_network/bd20558f-1a9e-4cc0-8634-2a716af8f617 to create new one
[2020-07-01 11:08:53,094: WARNING/chroma_core.services.http_agent.sessions] Destroying session mgs-1/linux/b27bf275-eb09-4b25-b3db-cee56ef63292 to create new one
[2020-07-01 11:08:53,094: WARNING/chroma_core.services.http_agent.sessions] Destroying session mgs-1/linux/b27bf275-eb09-4b25-b3db-cee56ef63292 to create new one
[2020-07-01 11:08:53,094: WARNING/chroma_core.services.http_agent.sessions] Destroying session mgs-1/action_runner/58c3a20b-5d6e-4ef7-89f2-a028742ddf33 to create new one
[2020-07-01 11:08:53,094: WARNING/chroma_core.services.http_agent.sessions] Destroying session mgs-1/action_runner/58c3a20b-5d6e-4ef7-89f2-a028742ddf33 to create new one
[2020-07-01 11:08:53,095: WARNING/chroma_core.services.http_agent.sessions] Destroying session mgs-1/systemd_journal/daddb397-f4a5-4f30-8adb-8a40441c8b6c to create new one
[2020-07-01 11:08:53,095: WARNING/chroma_core.services.http_agent.sessions] Destroying session mgs-1/systemd_journal/daddb397-f4a5-4f30-8adb-8a40441c8b6c to create new one
[2020-07-01 11:12:01,831: WARNING/http_agent_host_state] Agent restart on server mgs-1 at 2020-07-01 11:12:01.393699+00:00
[2020-07-01 11:12:01,864: WARNING/chroma_core.services.http_agent.sessions] Destroying session mgs-1/lustre/d5cb96e4-cddd-4f0f-8edc-4b2661152722 to create new one
[2020-07-01 11:12:01,864: WARNING/chroma_core.services.http_agent.sessions] Destroying session mgs-1/lustre/d5cb96e4-cddd-4f0f-8edc-4b2661152722 to create new one
[2020-07-01 11:12:01,864: WARNING/chroma_core.services.http_agent.sessions] Destroying session mgs-1/systemd_journal/364ab6df-5ca7-4b5d-8d6a-73b1e4a25f2d to create new one
[2020-07-01 11:12:01,864: WARNING/chroma_core.services.http_agent.sessions] Destroying session mgs-1/systemd_journal/364ab6df-5ca7-4b5d-8d6a-73b1e4a25f2d to create new one
[2020-07-01 11:12:01,865: WARNING/chroma_core.services.http_agent.sessions] Destroying session mgs-1/corosync/043b03d1-c9de-46be-8f57-f9d446131a5e to create new one
[2020-07-01 11:12:01,865: WARNING/chroma_core.services.http_agent.sessions] Destroying session mgs-1/corosync/043b03d1-c9de-46be-8f57-f9d446131a5e to create new one
[2020-07-01 11:12:01,865: WARNING/chroma_core.services.http_agent.sessions] Destroying session mgs-1/linux_network/e60dd04a-0487-477c-83c5-6f9de57a6a42 to create new one
[2020-07-01 11:12:01,865: WARNING/chroma_core.services.http_agent.sessions] Destroying session mgs-1/linux_network/e60dd04a-0487-477c-83c5-6f9de57a6a42 to create new one
[2020-07-01 11:12:01,865: WARNING/chroma_core.services.http_agent.sessions] Destroying session mgs-1/action_runner/ea99b7f0-ac39-47ac-ab1d-307d544570b8 to create new one
[2020-07-01 11:12:01,865: WARNING/chroma_core.services.http_agent.sessions] Destroying session mgs-1/action_runner/ea99b7f0-ac39-47ac-ab1d-307d544570b8 to create new one
[2020-07-01 11:12:01,866: WARNING/chroma_core.services.http_agent.sessions] Destroying session mgs-1/linux/71546456-4715-48d3-8cc1-776693260b06 to create new one
[2020-07-01 11:12:01,866: WARNING/chroma_core.services.http_agent.sessions] Destroying session mgs-1/linux/71546456-4715-48d3-8cc1-776693260b06 to create new one
[2020-07-01 11:12:01,877: WARNING/agent_views] Cancelling GET due to barrier 2020-07-01T11:12:01.393699+00:00Z 2020-07-01T11:08:52.911680+00:00Z
...skipping...
do          domainname  done
[2020-06-30 10:41:26,218: ERROR/rpc] ServiceRpcInterface._call: exception 'NoneType' object has no attribute 'id': AttributeError       traceback: Traceback (most recent call last):

  File "/usr/share/chroma-manager/chroma_core/services/rpc.py", line 107, in run
    "result": self.rpc._local_call(self.body["method"], *self.body["args"], **self.body["kwargs"]),

  File "/usr/share/chroma-manager/chroma_core/services/rpc.py", line 622, in _local_call
    return fn(*args, **kwargs)

  File "/usr/share/chroma-manager/chroma_core/services/job_scheduler/job_scheduler.py", line 1213, in create_filesystem
    mgt_data["volume_id"], reformat=mgt_data.get("reformat", False), **_target_kwargs(mgt_data)

  File "/usr/share/chroma-manager/chroma_core/models/target.py", line 339, in create_for_volume
    len(StonithNotEnabledAlert.filter_by_item_id(corosync_configuration.__class__, corosync_configuration.id))

AttributeError: 'NoneType' object has no attribute 'id'  
```
</details>

### sosreport
Attach any [`sosreport`s](https://whamcloud.github.io/Online-Help/docs/Install_Guide/ig_ch_15_appD_getting_help.html) for nodes relevant to this issue.

**Comment by jgrund** [comment]
This currently won't work. I'd suggest using a monitored profile if you'd like to work with a filesystem without HA.

**Comment by gustavo4passos** [comment]
@jgrund thank you for the quick response.
