### ISSUE TITLE
IML bugreport AutoConfigureCorosyncStep fails when setting up a new server

### ISSUE THREAD

**Issue by gustavo4passos** [whamcloud/integrated-manager-for-lustre#2043]
**Describe the bug**
Setting up a new server fails during the AutoConfigureCorosyncStep.  
I noticed #511 seemed to address the issue, so I'm not sure why it's happening to me.

**To Reproduce**
1. Go to the server page in the UI.
2. Add a new server and finish the deploy stage.
3. Select the base_managed_rh7 profile and continue configuration.
4. Error happens during the AutoConfigureCorosyncStep.

**Desktop (please complete the following information):**
 - OS: RHEL 7.6
 - Browser: Chrome
 - Version 81

### Version
What version of IML? 5.1.0
What Operating System? RHEL
What Operating System version? 7.6

### Logs:

**Arguments**
```json
{
  "corosync_configuration": "mgs-1 Corosync2 configuration",
  "prev_result": null
}
```

**Logs**
```
/sbin/ip route get 10.0.1.19: 0
10.0.1.19 dev eth0 src 10.0.1.20 
    cache 
```

**Backtrace**
```
Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/chroma_agent/device_plugins/action_runner.py", line 182, in run
    self.action, agent_daemon_context, self.args

  File "/usr/lib/python2.7/site-packages/chroma_agent/plugin_manager.py", line 321, in run
    return fn(**args)

  File "/usr/lib/python2.7/site-packages/chroma_agent/action_plugins/manage_corosync_common.py", line 38, in get_corosync_autoconfig
    ring1 = detect_ring1(ring0, ring1_ipaddr, ring1_prefix)

  File "/usr/lib/python2.7/site-packages/chroma_agent/lib/corosync.py", line 139, in detect_ring1
    iface.mcastport = find_unused_port(ring0)

  File "/usr/lib/python2.7/site-packages/chroma_agent/lib/corosync.py", line 182, in find_unused_port
    0, "tcp", "find unused port", persist=False, address=ring0.mcastaddr

  File "/usr/lib/python2.7/site-packages/iml_common/lib/firewall_control.py", line 72, in add_rule
    retval = self._add_address(address, proto)

  File "/usr/lib/python2.7/site-packages/iml_common/lib/firewall_control.py", line 222, in _add_address
    return self._address_rule("add", address, proto)

  File "/usr/lib/python2.7/site-packages/iml_common/lib/firewall_control.py", line 196, in _address_rule
    result = shell.Shell.run(arg_list)

  File "/usr/lib/python2.7/site-packages/chroma_agent/lib/shell.py", line 90, in run
    result = super(AgentShell, cls).run(arg_list, console_log, cls.monitor_func)

  File "/usr/lib/python2.7/site-packages/iml_common/lib/shell.py", line 126, in run
    result = cls._run(arg_list, logger, monitor_func, timeout, shell=shell)

  File "/usr/lib/python2.7/site-packages/iml_common/lib/shell.py", line 68, in _run
    p = subprocess.Popen(arg_list, stdout=stdout_fd, stderr=stderr_fd, close_fds=True, shell=shell)

  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)

  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception

OSError: [Errno 2] No such file or directory
```

**Comment by jgrund** [comment]
@gustavo4passos What profile are you trying to deploy?

**Comment by gustavo4passos** [comment]
@jgrund  I'm using the "Managed Storaged Server", that comes registered by default. It's in the file base_managed_RH7.profile. Here are its settings:

```json
{
  "ui_name": "Managed Storage Server",
  "managed": true,
  "worker": false,
  "name": "base_managed_rh7",
  "initial_state": "managed",
  "ntp": true,
  "corosync": false,
  "corosync2": true,
  "pacemaker": true,
  "ui_description": "A storage server suitable for creating new HA-enabled filesystem targets",
  "packages": [
    "python2-iml-agent-management",
    "kernel-devel-lustre",
    "pcs",
    "fence-agents",
    "fence-agents-virsh",
    "lustre-resource-agents",
    "lustre-ldiskfs-zfs"
  ],
  "repolist": [
    "base",
    "lustre-server"
  ],
  "validation": [
    {
      "description": "The profile is designed for version 7 of EL",
      "test": "distro_version < 8 and distro_version >= 7"
    }
  ]
}
```

**Comment by gustavo4passos** [comment]
@jgrund I was able to solve the issue.

In the module iml_common/lib/firewall_control.py, it would try to run a shell command with these args:
```python
arg_list = ["/usr/bin/firewall-cmd", "--%s-port=%s/%s" % (act, port, proto)]
```
However, ```/usr/bin/firewall-cmd``` didn't exist.  
It was solved by installing firewalld.

**Comment by jgrund** [comment]
We should be a bit smarter and first check if `firewalld` is installed / active prior to running commands.
