### ISSUE TITLE
Jenkins tests are flaky

### ISSUE THREAD

**Issue by mkpankov** [whamcloud/integrated-manager-for-lustre#2096]
The run
https://build.whamcloud.com/job/manager-for-lustre/1355/
for commit
https://github.com/whamcloud/integrated-manager-for-lustre/commit/0f987b4b6d74156120fe4cd0e2e8ee867a309803
was successful, but the run
https://build.whamcloud.com/job/manager-for-lustre/1369/
for commit
https://github.com/whamcloud/integrated-manager-for-lustre/commit/c18ec955007bf8b5a4923310eaccb946529991d6
wasn't.

The only difference in them is one empty line in a Rust source file.

**Comment by jgrund** [comment]
I'm going to close this, please open another issue with the cause of the failure in run #1369 (or at least the error from that run).

**Comment by jgrund** [comment]
That's the panic that ended up terminating the test, but is not the cause of the failure. 

The cause will be somewhere above that, prior to sosreports being collected.

**Comment by mkpankov** [comment]
It looks like the cause was this

```
12:46:12  [2mJul 21 09:46:12.175[0m [34mDEBUG[0m iml_system_test_utils::ssh: Running command iml filesystem detect on 10.73.10.10
12:46:12  [2mJul 21 09:46:12.175[0m [34mDEBUG[0m iml_cmd: Running cmd: Command { std: "ssh" "-o" "StrictHostKeyChecking=no" "-o" "UserKnownHostsFile=/dev/null" "-i" "id_rsa" "10.73.10.10" "iml filesystem detect", kill_on_drop: false }
12:46:12  Warning: Permanently added '10.73.10.10' (ECDSA) to the list of known hosts.
12:47:48  ✗ The following commands have failed:
12:47:48  Detecting filesystems
```

**Comment by jgrund** [comment]
`iml-rpm-system-test` seems ok

**Comment by jgrund** [comment]
for iml-docker-system-test you need to look at the logs within the adm sosreport and find any tracebacks, that will point at the underlying cause.

**Comment by mkpankov** [comment]
> iml-rpm-system-test seems ok
I though it wouldn't create diagnostics in that case

> for iml-docker-system-test you need to look at the logs within the adm sosreport and find any tracebacks, that will point at the underlying cause.

Will do

**Comment by jgrund** [comment]
> I thought it wouldn't create diagnostics in that case

Diagnostics are created for every run regardless of pass / fail state.

**Comment by mkpankov** [comment]
Tracebacks from `adm` from failing run:

```
plugin_runner.log:302:[2020-07-21 09:24:44,420: ERROR/rpc] RunOneRpc: exception calling setup_host: Traceback (most recent call last):
plugin_runner.log:347:[2020-07-21 09:24:44,711: ERROR/rpc] RunOneRpc: exception calling setup_host: Traceback (most recent call last):
plugin_runner.log:363:[2020-07-21 09:24:44,713: ERROR/rpc] RunOneRpc: exception calling setup_host: Traceback (most recent call last):
job_scheduler.log:817:[2020-07-21 09:24:44,448: DEBUG/rpc] Completed rpc: setup_host, id: 57330de0-ffe5-4f7f-8ab0-aac21e876630, result: {u'exception_type': u'AssertionError', u'exception': u'', u'traceback': u'Traceback (most recent call last):\n\n  File "/usr/share/chroma-manager/chroma_core/services/rpc.py", line 107, in run\n    "result": self.rpc._local_call(self.body["method"], *self.body["args"], **self.body["kwargs"]),\n\n  File "/usr/share/chroma-manager/chroma_core/services/rpc.py", line 622, in _local_call\n    return fn(*args, **kwargs)\n\n  File "/usr/share/chroma-manager/chroma_core/services/plugin_runner/__init__.py", line 24, in setup_host\n    self.handlers[plugin_name].setup_host(host_id, data)\n\n  File "/usr/share/chroma-manager/chroma_core/services/plugin_runner/agent_daemon.py", line 91, in setup_host\n    assert session is not None\n\nAssertionError\n', u'result': None, u'request_id': u'57330de0-ffe5-4f7f-8ab0-aac21e876630'}
job_scheduler.log:887:[2020-07-21 09:24:44,720: DEBUG/rpc] Completed rpc: setup_host, id: c9ae7d6c-7e26-4928-a404-c49cf01fc966, result: {u'exception_type': u'AssertionError', u'exception': u'', u'traceback': u'Traceback (most recent call last):\n\n  File "/usr/share/chroma-manager/chroma_core/services/rpc.py", line 107, in run\n    "result": self.rpc._local_call(self.body["method"], *self.body["args"], **self.body["kwargs"]),\n\n  File "/usr/share/chroma-manager/chroma_core/services/rpc.py", line 622, in _local_call\n    return fn(*args, **kwargs)\n\n  File "/usr/share/chroma-manager/chroma_core/services/plugin_runner/__init__.py", line 24, in setup_host\n    self.handlers[plugin_name].setup_host(host_id, data)\n\n  File "/usr/share/chroma-manager/chroma_core/services/plugin_runner/agent_daemon.py", line 91, in setup_host\n    assert session is not None\n\nAssertionError\n', u'result': None, u'request_id': u'c9ae7d6c-7e26-4928-a404-c49cf01fc966'}
job_scheduler.log:899:[2020-07-21 09:24:44,750: DEBUG/rpc] Completed rpc: setup_host, id: 9d9ff33d-50dd-4291-b1f7-226994fd54de, result: {u'exception_type': u'AssertionError', u'exception': u'', u'traceback': u'Traceback (most recent call last):\n\n  File "/usr/share/chroma-manager/chroma_core/services/rpc.py", line 107, in run\n    "result": self.rpc._local_call(self.body["method"], *self.body["args"], **self.body["kwargs"]),\n\n  File "/usr/share/chroma-manager/chroma_core/services/rpc.py", line 622, in _local_call\n    return fn(*args, **kwargs)\n\n  File "/usr/share/chroma-manager/chroma_core/services/plugin_runner/__init__.py", line 24, in setup_host\n    self.handlers[plugin_name].setup_host(host_id, data)\n\n  File "/usr/share/chroma-manager/chroma_core/services/plugin_runner/agent_daemon.py", line 91, in setup_host\n    assert session is not None\n\nAssertionError\n', u'result': None, u'request_id': u'9d9ff33d-50dd-4291-b1f7-226994fd54de'}
```

Details:
```
[2020-07-21 09:24:44,420: ERROR/rpc] RunOneRpc: exception calling setup_host: Traceback (most recent call last):

  File "/usr/share/chroma-manager/chroma_core/services/rpc.py", line 107, in run
    "result": self.rpc._local_call(self.body["method"], *self.body["args"], **self.body["kwargs"]),

  File "/usr/share/chroma-manager/chroma_core/services/rpc.py", line 622, in _local_call
    return fn(*args, **kwargs)

  File "/usr/share/chroma-manager/chroma_core/services/plugin_runner/__init__.py", line 24, in setup_host
    self.handlers[plugin_name].setup_host(host_id, data)

  File "/usr/share/chroma-manager/chroma_core/services/plugin_runner/agent_daemon.py", line 91, in setup_host
    assert session is not None

AssertionError
```

```
[2020-07-21 09:24:44,448: DEBUG/rpc] Completed rpc: setup_host, id: 57330de0-ffe5-4f7f-8ab0-aac21e876630, result: {u'exception_type': u'AssertionError', u'exception': u'', u'traceback': u'Traceback (most recent call last):\n\n  File "/usr/share/chroma-manager/chroma_core/services/rpc.py", line 107, in run\n    "result": self.rpc._local_call(self.body["method"], *self.body["args"], **self.body["kwargs"]),\n\n  File "/usr/share/chroma-manager/chroma_core/services/rpc.py", line 622, in _local_call\n    return fn(*args, **kwargs)\n\n  File "/usr/share/chroma-manager/chroma_core/services/plugin_runner/__init__.py", line 24, in setup_host\n    self.handlers[plugin_name].setup_host(host_id, data)\n\n  File "/usr/share/chroma-manager/chroma_core/services/plugin_runner/agent_daemon.py", line 91, in setup_host\n    assert session is not None\n\nAssertionError\n', u'result': None, u'request_id': u'57330de0-ffe5-4f7f-8ab0-aac21e876630'}
```

**Comment by mkpankov** [comment]
Looks like the actual error is this
```
2020-07-21T09:47:42.069550166Z [2020-07-21 09:47:42,069: ERROR/job_scheduler] Job 34 step 1 encountered an agent error: Could not contact server oss2.local no session after 30 seconds
```
