### ISSUE TITLE
Jenkins failed in Archiving artifacts

### ISSUE THREAD

**Issue by mkpankov** [whamcloud/integrated-manager-for-lustre#2097]
https://build.whamcloud.com/job/manager-for-lustre/1369/consoleFull

Looks like it didn't expect to find no sosreports

```
02:27:42  Archiving artifacts
02:27:43  ‘**/vagrant/sosreport_docker*/*.tar.xz’ doesn’t match anything: ‘**’ exists but not ‘**/vagrant/sosreport_docker*/*.tar.xz’
02:27:43  Error when executing always post condition:
02:27:43  hudson.AbortException: No artifacts found that match the file pattern "**/vagrant/sosreport_docker*/*.tar.xz". Configuration error?
02:27:43  	at hudson.tasks.ArtifactArchiver.perform(ArtifactArchiver.java:275)
02:27:43  	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
02:27:43  	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
02:27:43  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
02:27:43  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
02:27:43  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02:27:43  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
02:27:43  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
02:27:43  	at java.lang.Thread.run(Thread.java:748)
02:27:43  
02:27:43  [Pipeline] }
02:27:43  [Pipeline] // withEnv
02:27:43  [Pipeline] }
02:27:43  [Pipeline] // node
02:27:43  [Pipeline] }
02:27:43  [Pipeline] // stage
02:27:43  [Pipeline] }
02:27:43  Failed in branch iml-docker-system-test
02:27:43  [Pipeline] // parallel
02:27:43  [Pipeline] }
02:27:43  [Pipeline] // stage
02:27:43  [Pipeline] }
02:27:43  [Pipeline] // withEnv
02:27:43  [Pipeline] End of Pipeline
02:27:43  Setting status of 25b8bc6fa56f2f60d34a985f7e61a8f49554fcc9 to FAILURE with url https://build.whamcloud.com/job/manager-for-lustre/1382/ and message: ' '
02:27:43  Using context: IML Build & Test
02:27:43  ERROR: No artifacts found that match the file pattern "**/vagrant/sosreport_rpm*/*.tar.xz". Configuration error?
02:27:43  Finished: FAILURE
```

**Comment by ip1981** [comment]
There is a switch to make artifacts optional.

**Comment by johnsonw** [comment]
Hmm the sosreports should be there. I'm investigating.

**Comment by johnsonw** [comment]
We need to land this: https://github.com/whamcloud/integrated-manager-for-lustre/pull/2088 and it should resolve the issue.
