### ISSUE TITLE
Job scheduler error when running `iml filesystem detect` after taking two snapshots

### ISSUE THREAD

**Issue by mkpankov** [whamcloud/integrated-manager-for-lustre#2213]
```
[2020-09-03 11:25:23,518: ERROR/job_scheduler] Job 104 step 1 encountered an error: [u'Cannot have multiple MGS mounts on host mds1.local']:Traceback (most recent call last):
  File "/usr/share/chroma-manager/chroma_core/services/job_scheduler/job_scheduler.py", line 346, in _run
    result = step.run(args)
  File "/usr/share/chroma-manager/chroma_core/models/host.py", line 983, in run
    DetectScan(self).run(host_data)
  File "/usr/share/chroma-manager/chroma_core/lib/detection.py", line 60, in run
    self.learn_target_mounts()
  File "/usr/share/chroma-manager/chroma_core/lib/detection.py", line 334, in learn_target_mounts
    target=target, host=host, volume_node=volumenode
  File "/usr/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 466, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 500, in _create_object_from_params
    obj = self.create(**params)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/share/chroma-manager/chroma_core/models/target.py", line 1827, in save
    raise ValidationError("Cannot have multiple MGS mounts on host %s" % self.host.address)
ValidationError: [u'Cannot have multiple MGS mounts on host mds1.local']
```

**Comment by mkpankov** [comment]
```
[root@mds1 vagrant]# lctl get_param mgs.MGS.*
mgs.MGS.uuid=MGS
mgs.MGS.filesystems=1ef1c0e5
0b93f8b7
zfsmo
mgs.MGS.fstype=zfs
mgs.MGS.hash_stats=
name                                                               cur   min   max theta t-min t-max flags rehash   count  maxdep maxdepb distribution
UUID_HASH                                                          128   128  4096 0.031 0.500 2.000  0x284      0       4      -1      -1 4/0/0/0/0/0/0/0
NID_HASH                                                           128   128  4096 0.031 0.500 2.000  0x284      0       4      -1      -1 4/0/0/0/0/0/0/0
NID_STATS                                                          128   128  4096 0.031 0.500 2.000  0x284      0       4      -1      -1 4/0/0/0/0/0/0/0
mgs.MGS.ir_timeout=400
mgs.MGS.mntdev=mgt/mgt
mgs.MGS.num_exports=4
```

**Comment by mkpankov** [comment]
```
[root@mds1 vagrant]# mount
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
devtmpfs on /dev type devtmpfs (rw,nosuid,size=1928724k,nr_inodes=482181,mode=755)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,mode=755)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpuacct,cpu)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_prio,net_cls)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
configfs on /sys/kernel/config type configfs (rw,relatime)
/dev/sda1 on / type xfs (rw,relatime,attr2,inode64,noquota)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=25,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=15807)
mqueue on /dev/mqueue type mqueue (rw,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
sunrpc on /var/lib/nfs/rpc_pipefs type rpc_pipefs (rw,relatime)
mgt on /mgt type zfs (rw,xattr,noacl)
mdt0 on /mdt0 type zfs (rw,xattr,noacl)
mgt/mgt on /lustre/zfsmo/mgs type lustre (ro,svname=MGS,nosvc,mgs,osd=osd-zfs)
mdt0/mdt0 on /lustre/zfsmo/mdt0 type lustre (ro,svname=zfsmo-MDT0000,mgsnode=10.73.20.11@tcp:10.73.20.12@tcp,osd=osd-zfs)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=387944k,mode=700,uid=1000,gid=1000)
```

**Comment by jgrund** [comment]
What does targets table say?

**Comment by mkpankov** [comment]
```
chroma=# select * from targets;
  state  |     name      | active_host_id | host_ids | filesystems |         uuid         |     mount_path      
---------+---------------+----------------+----------+-------------+----------------------+---------------------
 mounted | zfsmo-OST0000 |              3 | {3,4}    | {zfsmo}     | 15315421109648966747 | /lustre/zfsmo/ost0
 mounted | zfsmo-OST0001 |              3 | {3,4}    | {zfsmo}     | 16130459837043950546 | /lustre/zfsmo/ost1
 mounted | zfsmo-OST0002 |              3 | {3,4}    | {zfsmo}     | 16809848044032475239 | /lustre/zfsmo/ost2
 mounted | zfsmo-OST0009 |              3 | {3,4}    | {zfsmo}     | 16616855860131431947 | /lustre/zfsmo/ost9
 mounted | MGS           |              1 | {1,2}    | {zfsmo}     | 621614175877281325   | /lustre/zfsmo/mgs
 mounted | zfsmo-MDT0000 |              1 | {1,2}    | {zfsmo}     | 16366567103101092488 | /lustre/zfsmo/mdt0
 mounted | zfsmo-OST000a |              4 | {4,3}    | {zfsmo}     | 6115881651101987850  | /lustre/zfsmo/ost10
 mounted | zfsmo-OST000b |              4 | {4,3}    | {zfsmo}     | 8307962409263197395  | /lustre/zfsmo/ost11
 mounted | zfsmo-OST000c |              4 | {4,3}    | {zfsmo}     | 8279382904473433322  | /lustre/zfsmo/ost12
 mounted | zfsmo-OST000d |              4 | {4,3}    | {zfsmo}     | 15342920231478714702 | /lustre/zfsmo/ost13
 mounted | zfsmo-MDT0001 |              2 | {2,1}    | {zfsmo}     | 10547742626673050506 | /lustre/zfsmo/mdt1
 mounted | zfsmo-OST000e |              4 | {4,3}    | {zfsmo}     | 6856388935167211930  | /lustre/zfsmo/ost14
 mounted | zfsmo-OST000f |              4 | {4,3}    | {zfsmo}     | 9232538781925590650  | /lustre/zfsmo/ost15
 mounted | zfsmo-OST0010 |              4 | {4,3}    | {zfsmo}     | 10144205821323061662 | /lustre/zfsmo/ost16
 mounted | zfsmo-OST0011 |              4 | {4,3}    | {zfsmo}     | 6329551814587036369  | /lustre/zfsmo/ost17
 mounted | zfsmo-OST0012 |              4 | {4,3}    | {zfsmo}     | 17523622627750641395 | /lustre/zfsmo/ost18
 mounted | zfsmo-OST0013 |              4 | {4,3}    | {zfsmo}     | 8179215271877355515  | /lustre/zfsmo/ost19
 mounted | zfsmo-OST0003 |              3 | {3,4}    | {zfsmo}     | 16323203364943692562 | /lustre/zfsmo/ost3
 mounted | zfsmo-OST0004 |              3 | {3,4}    | {zfsmo}     | 3348886755427763438  | /lustre/zfsmo/ost4
 mounted | zfsmo-OST0005 |              3 | {3,4}    | {zfsmo}     | 6164031043670620805  | /lustre/zfsmo/ost5
 mounted | zfsmo-OST0006 |              3 | {3,4}    | {zfsmo}     | 6570776925687703032  | /lustre/zfsmo/ost6
 mounted | zfsmo-OST0007 |              3 | {3,4}    | {zfsmo}     | 18383856045591558839 | /lustre/zfsmo/ost7
 mounted | zfsmo-OST0008 |              3 | {3,4}    | {zfsmo}     | 4386736002751448922  | /lustre/zfsmo/ost8
(23 rows)
```

**Comment by jgrund** [comment]
We no longer use job_scheduler when detecting a filesystem.
