### ISSUE TITLE
mount.lustre: mount /dev/sdc at /mnt/testfs-OST0000 failed: File exists

### ISSUE THREAD

**Issue by brianjmurrell** [whamcloud/integrated-manager-for-lustre#256]
In a [test run](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/1139/arch=x86_64,distro=el7) we got yet a different kind of `mount` error from Lustre:

```
test_writeconf_conf_params (tests.integration.shared_storage_configuration.test_conf_params.TestConfParams) ... FAIL
FAIL
Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_conf_params.py", line 65, in test_writeconf_conf_params
    self._create_with_params()
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_conf_params.py", line 36, in _create_with_params
    'conf_params': {'llite.max_cached_mb': '16'}})
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 432, in create_filesystem
    timeout = LONG_TEST_TIMEOUT
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 336, in wait_for_command
    self.assertFalse(command['errored'] or command['cancelled'], command)
AssertionError: {u'jobs': [u'/api/job/29/', u'/api/job/30/', u'/api/job/31/', u'/api/job/32/', u'/api/job/33/', u'/api/job/34/', u'/api/job/35/', u'/api/job/36/', u'/api/job/37/', u'/api/job/38/', u'/api/job/39/', u'/api/job/40/', u'/api/job/41/', u'/api/job/42/', u'/api/job/43/', u'/api/job/44/', u'/api/job/45/'], u'complete': True, u'created_at': u'2017-08-30T23:43:15.192326', u'message': u'Creating filesystem testfs', u'cancelled': True, u'errored': True, u'resource_uri': u'/api/command/9/', u'id': 9, u'logs': u'\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'}
-------------------- >> begin captured stdout << ---------------------
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/11/', u'volume_nodes': [{u'use': True, u'volume_id': 1, u'primary': True, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14', u'host_id': 2, u'resource_uri': u'/api/volume_node/2/', u'id': 2, u'host_label': u'lotus-49vm16.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 1, u'primary': False, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14', u'host_id': 1, u'resource_uri': u'/api/volume_node/7/', u'id': 7, u'host_label': u'lotus-49vm15.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk14', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/1/', u'id': 1, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/12/', u'volume_nodes': [{u'use': True, u'volume_id': 2, u'primary': False, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk11', u'host_id': 2, u'resource_uri': u'/api/volume_node/3/', u'id': 3, u'host_label': u'lotus-49vm16.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 2, u'primary': True, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk11', u'host_id': 1, u'resource_uri': u'/api/volume_node/8/', u'id': 8, u'host_label': u'lotus-49vm15.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk11', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/2/', u'id': 2, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/13/', u'volume_nodes': [{u'use': True, u'volume_id': 3, u'primary': False, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk13', u'host_id': 2, u'resource_uri': u'/api/volume_node/4/', u'id': 4, u'host_label': u'lotus-49vm16.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 3, u'primary': True, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk13', u'host_id': 1, u'resource_uri': u'/api/volume_node/9/', u'id': 9, u'host_label': u'lotus-49vm15.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk13', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/3/', u'id': 3, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/14/', u'volume_nodes': [{u'use': True, u'volume_id': 4, u'primary': True, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk12', u'host_id': 2, u'resource_uri': u'/api/volume_node/5/', u'id': 5, u'host_label': u'lotus-49vm16.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 4, u'primary': False, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk12', u'host_id': 1, u'resource_uri': u'/api/volume_node/10/', u'id': 10, u'host_label': u'lotus-49vm15.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk12', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/4/', u'id': 4, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/10/', u'volume_nodes': [{u'use': True, u'volume_id': 5, u'primary': False, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk15', u'host_id': 2, u'resource_uri': u'/api/volume_node/1/', u'id': 1, u'host_label': u'lotus-49vm16.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 5, u'primary': True, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk15', u'host_id': 1, u'resource_uri': u'/api/volume_node/6/', u'id': 6, u'host_label': u'lotus-49vm15.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk15', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/5/', u'id': 5, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/11/', u'volume_nodes': [{u'use': True, u'volume_id': 1, u'primary': True, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14', u'host_id': 2, u'resource_uri': u'/api/volume_node/2/', u'id': 2, u'host_label': u'lotus-49vm16.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 1, u'primary': False, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk14', u'host_id': 1, u'resource_uri': u'/api/volume_node/7/', u'id': 7, u'host_label': u'lotus-49vm15.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk14', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/1/', u'id': 1, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/12/', u'volume_nodes': [{u'use': True, u'volume_id': 2, u'primary': False, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk11', u'host_id': 2, u'resource_uri': u'/api/volume_node/3/', u'id': 3, u'host_label': u'lotus-49vm16.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 2, u'primary': True, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk11', u'host_id': 1, u'resource_uri': u'/api/volume_node/8/', u'id': 8, u'host_label': u'lotus-49vm15.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk11', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/2/', u'id': 2, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/13/', u'volume_nodes': [{u'use': True, u'volume_id': 3, u'primary': False, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk13', u'host_id': 2, u'resource_uri': u'/api/volume_node/4/', u'id': 4, u'host_label': u'lotus-49vm16.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 3, u'primary': True, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk13', u'host_id': 1, u'resource_uri': u'/api/volume_node/9/', u'id': 9, u'host_label': u'lotus-49vm15.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk13', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/3/', u'id': 3, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/14/', u'volume_nodes': [{u'use': True, u'volume_id': 4, u'primary': True, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk12', u'host_id': 2, u'resource_uri': u'/api/volume_node/5/', u'id': 5, u'host_label': u'lotus-49vm16.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 4, u'primary': False, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk12', u'host_id': 1, u'resource_uri': u'/api/volume_node/10/', u'id': 10, u'host_label': u'lotus-49vm15.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk12', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/4/', u'id': 4, u'size': u'10737418240'}
{u'status': u'configured-ha', u'kind': u'SCSI device', u'storage_resource': u'/api/storage_resource/10/', u'volume_nodes': [{u'use': True, u'volume_id': 5, u'primary': False, u'host': u'/api/host/2/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk15', u'host_id': 2, u'resource_uri': u'/api/volume_node/1/', u'id': 1, u'host_label': u'lotus-49vm16.lotus.hpdd.lab.intel.com'}, {u'use': True, u'volume_id': 5, u'primary': True, u'host': u'/api/host/1/', u'path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk15', u'host_id': 1, u'resource_uri': u'/api/volume_node/6/', u'id': 6, u'host_label': u'lotus-49vm15.lotus.hpdd.lab.intel.com'}], u'filesystem_type': None, u'label': u'disk15', u'usable_for_lustre': True, u'resource_uri': u'/api/volume/5/', u'id': 5, u'size': u'10737418240'}
COMMAND 9: FAILED
-----------------------------------------------------------
{u'jobs': [u'/api/job/29/', u'/api/job/30/', u'/api/job/31/', u'/api/job/32/', u'/api/job/33/', u'/api/job/34/', u'/api/job/35/', u'/api/job/36/', u'/api/job/37/', u'/api/job/38/', u'/api/job/39/', u'/api/job/40/', u'/api/job/41/', u'/api/job/42/', u'/api/job/43/', u'/api/job/44/', u'/api/job/45/'], u'complete': True, u'created_at': u'2017-08-30T23:43:15.192326', u'message': u'Creating filesystem testfs', u'cancelled': True, u'errored': True, u'resource_uri': u'/api/command/9/', u'id': 9, u'logs': u'\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'}

Job 40 Errored (Register testfs-OST0000):
{u'commands': [u'/api/command/9/'], u'write_locks': [{u'locked_item_content_type_id': 91, u'locked_item_id': 3, u'locked_item_uri': u'/api/target/3/', u'resource_uri': u''}], u'description': u'Register testfs-OST0000', u'read_locks': [{u'locked_item_content_type_id': 10, u'locked_item_id': 1, u'locked_item_uri': u'/api/lnet_configuration/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 93, u'locked_item_id': 1, u'locked_item_uri': u'/api/target/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 92, u'locked_item_id': 2, u'locked_item_uri': u'/api/target/2/', u'resource_uri': u''}, {u'locked_item_content_type_id': 109, u'locked_item_id': 1, u'locked_item_uri': u'/api/filesystem/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 10, u'locked_item_id': 1, u'locked_item_uri': u'/api/lnet_configuration/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 49, u'locked_item_id': 1, u'locked_item_uri': u'/api/pacemaker_configuration/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 10, u'locked_item_id': 2, u'locked_item_uri': u'/api/lnet_configuration/2/', u'resource_uri': u''}, {u'locked_item_content_type_id': 49, u'locked_item_id': 2, u'locked_item_uri': u'/api/pacemaker_configuration/2/', u'resource_uri': u''}, {u'locked_item_content_type_id': 109, u'locked_item_id': 1, u'locked_item_uri': u'/api/filesystem/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 10, u'locked_item_id': 1, u'locked_item_uri': u'/api/lnet_configuration/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 49, u'locked_item_id': 1, u'locked_item_uri': u'/api/pacemaker_configuration/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 10, u'locked_item_id': 2, u'locked_item_uri': u'/api/lnet_configuration/2/', u'resource_uri': u''}, {u'locked_item_content_type_id': 49, u'locked_item_id': 2, u'locked_item_uri': u'/api/pacemaker_configuration/2/', u'resource_uri': u''}], u'class_name': u'RegisterTargetJob', u'step_results': {u'/api/step/79/': None}, u'created_at': u'2017-08-30T23:43:15.458049', u'modified_at': u'2017-08-30T23:43:15.458020', u'available_transitions': [], u'state': u'complete', u'steps': [u'/api/step/79/'], u'cancelled': False, u'errored': True, u'wait_for': [u'/api/job/35/', u'/api/job/29/', u'/api/job/38/'], u'id': 40, u'resource_uri': u'/api/job/40/'}

Step 79 failed:
step_count: 2
console: modprobe osd_ldiskfs: 0


lctl set_param debug=-1: 0
debug=-1


lctl set_param debug_mb=200: 0
debug_mb=200


strace -o /var/tmp/mount.strace -f mount --verbose -t lustre /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk13 /mnt/testfs-OST0000: 17
arg[0] = /sbin/mount.lustre
arg[1] = -v
arg[2] = -o
arg[3] = rw
arg[4] = /dev/sdc
arg[5] = /mnt/testfs-OST0000
source = /dev/sdc (/dev/sdc), target = /mnt/testfs-OST0000
options = rw
checking for existing Lustre data: found
Reading CONFIGS/mountdata
Writing CONFIGS/mountdata
mounting device /dev/sdc at /mnt/testfs-OST0000, flags=0x1000000 options=,errors=remount-ro,,osd=osd-ldiskfs,mgsnode=10.14.80.136@tcp:10.14.80.137@tcp,virgin,update,param=mgsnode=10.14.80.136@tcp:10.14.80.137@tcp,param=failover.node=10.14.80.137@tcp,svname=testfs-OST0000,device=/dev/sdc

mount.lustre: increased /sys/block/sdc/queue/max_sectors_kb from 512 to 16384
mount.lustre: mount /dev/sdc at /mnt/testfs-OST0000 failed: File exists retries left: 0
mount.lustre: mount /dev/sdc at /mnt/testfs-OST0000 failed: File exists


description: RegisterTargetStep: {'device_path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk13', 'primary_host': <ManagedHost: lotus-49vm15.lotus.hpdd.lab.intel.com>, 'mount_point': u'/mnt/testfs-OST0000', 'backfstype': 'ldiskfs', 'target': <ManagedTarget: testfs-OST0000>}
class_name: RegisterTargetStep
backtrace: Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/chroma_agent/device_plugins/action_runner.py", line 164, in run

  File "/usr/lib/python2.7/site-packages/chroma_agent/plugin_manager.py", line 305, in run

  File "/usr/lib/python2.7/site-packages/chroma_agent/action_plugins/manage_targets.py", line 282, in register_target

  File "/usr/lib/python2.7/site-packages/iml_common/filesystems/filesystem.py", line 156, in mount
    raise RuntimeError("Error (%s) mounting '%s': '%s' '%s'" % (result.rc, mount_point, result.stdout, result.stderr))

RuntimeError: Error (17) mounting '/mnt/testfs-OST0000': 'arg[0] = /sbin/mount.lustre
arg[1] = -v
arg[2] = -o
arg[3] = rw
arg[4] = /dev/sdc
arg[5] = /mnt/testfs-OST0000
source = /dev/sdc (/dev/sdc), target = /mnt/testfs-OST0000
options = rw
checking for existing Lustre data: found
Reading CONFIGS/mountdata
Writing CONFIGS/mountdata
mounting device /dev/sdc at /mnt/testfs-OST0000, flags=0x1000000 options=,errors=remount-ro,,osd=osd-ldiskfs,mgsnode=10.14.80.136@tcp:10.14.80.137@tcp,virgin,update,param=mgsnode=10.14.80.136@tcp:10.14.80.137@tcp,param=failover.node=10.14.80.137@tcp,svname=testfs-OST0000,device=/dev/sdc
' 'mount.lustre: increased /sys/block/sdc/queue/max_sectors_kb from 512 to 16384
mount.lustre: mount /dev/sdc at /mnt/testfs-OST0000 failed: File exists retries left: 0
mount.lustre: mount /dev/sdc at /mnt/testfs-OST0000 failed: File exists
'

created_at: 2017-08-30T23:44:04.400816
args: {u'device_path': u'/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_disk13', u'primary_host': u'lotus-49vm15.lotus.hpdd.lab.intel.com', u'mount_point': u'/mnt/testfs-OST0000', u'backfstype': u'ldiskfs', u'target': u'testfs-OST0000'}
modified_at: 2017-08-30T23:44:15.961027
step_index: 0
state: failed
result: 
resource_uri: /api/step/79/
id: 79
log: 


--------------------- >> end captured stdout << ----------------------
```

**Comment by brianjmurrell** [comment]
[Another](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/1139/arch=x86_64,distro=el7)
