### ISSUE TITLE
AssertionError: Timed out waiting for         self.wait_for_items_length(lambda: self.get_list("/api/ha_cluster/"), self.EXPECTED_CLUSTER_COUNT)

### ISSUE THREAD

**Issue by brianjmurrell** [whamcloud/integrated-manager-for-lustre#260]
In a [test run](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/arch=x86_64,distro=el7/1149):

```
test_ha_clusters_are_distinct (tests.integration.shared_storage_configuration.test_ha_clustering.TestHaClusters) ... ERROR
ERROR
Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_ha_clustering.py", line 25, in setUp
    self.wait_for_items_length(lambda: self.get_list("/api/ha_cluster/"), self.EXPECTED_CLUSTER_COUNT)
  File "/usr/share/chroma-manager/tests/integration/core/utility_testcase.py", line 152, in wait_for_items_length
    self.assertNotEqual(0, timeout, "Timed out waiting for %s." % inspect.getsource(fetch_items))
AssertionError: Timed out waiting for         self.wait_for_items_length(lambda: self.get_list("/api/ha_cluster/"), self.EXPECTED_CLUSTER_COUNT)
```

**Comment by brianjmurrell** [comment]
[Another](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/2877/arch=x86_64,distro=el7)
