### ISSUE TITLE
PacemakerError: cibadmin --query --local timed out after 10 seconds: rc: 107, stderr: Signon to CIB failed: Transport endpoint is not connected Init failed, could not perform requested operations

### ISSUE THREAD

**Issue by brianjmurrell** [whamcloud/integrated-manager-for-lustre#269]
[In](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/arch=x86_64,distro=el7/1226]:

```
test_reboot_event (tests.integration.shared_storage_configuration.test_alerting.TestEvents) ... FAIL
FAIL
Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_alerting.py", line 14, in test_reboot_event
    self.add_hosts([self.TEST_SERVERS[0]['address']])
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 308, in add_hosts
    self._add_hosts(addresses_to_add, auth_type)
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 269, in _add_hosts
    self.set_host_profiles(self.get_hosts(addresses))
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 236, in set_host_profiles
    lambda: check_for_HYD_2849_4050())
  File "/usr/share/chroma-manager/tests/integration/core/utility_testcase.py", line 210, in _fetch_help
    return assert_test()
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 233, in <lambda>
    self._fetch_help(lambda: self.wait_for_commands(self.chroma_manager, command_ids, timeout=INSTALL_TIMEOUT),
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 347, in wait_for_commands
    self.wait_for_command(chroma_manager, command_id, timeout, verify_successful)
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 336, in wait_for_command
    self.assertFalse(command['errored'] or command['cancelled'], command)
AssertionError: {u'jobs': [u'/api/job/3/', u'/api/job/4/', u'/api/job/5/', u'/api/job/6/', u'/api/job/7/', u'/api/job/8/', u'/api/job/9/', u'/api/job/10/', u'/api/job/11/', u'/api/job/12/', u'/api/job/13/'], u'complete': True, u'created_at': u'2017-09-06T05:43:41.033015', u'message': u'Setup managed host lotus-10vm15.lotus.hpdd.lab.intel.com', u'cancelled': True, u'errored': True, u'resource_uri': u'/api/command/3/', u'id': 3, u'logs': u'\n\n\n\n\n\n\n\n\n\n\n\n\n'}
-------------------- >> begin captured stdout << ---------------------
COMMAND 3: FAILED
-----------------------------------------------------------
{u'jobs': [u'/api/job/3/', u'/api/job/4/', u'/api/job/5/', u'/api/job/6/', u'/api/job/7/', u'/api/job/8/', u'/api/job/9/', u'/api/job/10/', u'/api/job/11/', u'/api/job/12/', u'/api/job/13/'], u'complete': True, u'created_at': u'2017-09-06T05:43:41.033015', u'message': u'Setup managed host lotus-10vm15.lotus.hpdd.lab.intel.com', u'cancelled': True, u'errored': True, u'resource_uri': u'/api/command/3/', u'id': 3, u'logs': u'\n\n\n\n\n\n\n\n\n\n\n\n\n'}

Job 10 Errored (Configure Pacemaker on lotus-10vm15.lotus.hpdd.lab.intel.com.):
{u'commands': [u'/api/command/3/'], u'write_locks': [{u'locked_item_content_type_id': 49, u'locked_item_id': 1, u'locked_item_uri': u'/api/pacemaker_configuration/1/', u'resource_uri': u''}], u'description': u'Configure Pacemaker on lotus-10vm15.lotus.hpdd.lab.intel.com.', u'read_locks': [{u'locked_item_content_type_id': 65, u'locked_item_id': 1, u'locked_item_uri': u'/api/host/1/', u'resource_uri': u''}, {u'locked_item_content_type_id': 43, u'locked_item_id': 1, u'locked_item_uri': u'/api/corosync_configuration/1/', u'resource_uri': u''}], u'class_name': u'ConfigurePacemakerJob', u'step_results': {u'/api/step/16/': None, u'/api/step/15/': None}, u'created_at': u'2017-09-06T05:43:41.181051', u'modified_at': u'2017-09-06T05:43:41.181021', u'available_transitions': [], u'state': u'complete', u'steps': [u'/api/step/15/', u'/api/step/16/'], u'cancelled': False, u'errored': True, u'wait_for': [u'/api/job/9/', u'/api/job/3/'], u'id': 10, u'resource_uri': u'/api/job/10/'}

Step 16 failed:
step_count: 3
console: systemctl is-active corosync: 0
active


systemctl enable pacemaker: 0

Created symlink from /etc/systemd/system/multi-user.target.wants/pacemaker.service to /usr/lib/systemd/system/pacemaker.service.

systemctl stop pacemaker: 0


systemctl is-active pacemaker: 3
inactive


systemctl start pacemaker: 0


systemctl is-active pacemaker: 0
active


cibadmin --query --local: 107

Signon to CIB failed: Transport endpoint is not connected
Init failed, could not perform requested operations

cibadmin --query --local: 107

Signon to CIB failed: Transport endpoint is not connected
Init failed, could not perform requested operations

cibadmin --query --local: 107

Signon to CIB failed: Transport endpoint is not connected
Init failed, could not perform requested operations

cibadmin --query --local: 107

Signon to CIB failed: Transport endpoint is not connected
Init failed, could not perform requested operations

cibadmin --query --local: 107

Signon to CIB failed: Transport endpoint is not connected
Init failed, could not perform requested operations

cibadmin --query --local: 107

Signon to CIB failed: Transport endpoint is not connected
Init failed, could not perform requested operations

cibadmin --query --local: 107

Signon to CIB failed: Transport endpoint is not connected
Init failed, could not perform requested operations

cibadmin --query --local: 107

Signon to CIB failed: Transport endpoint is not connected
Init failed, could not perform requested operations

cibadmin --query --local: 107

Signon to CIB failed: Transport endpoint is not connected
Init failed, could not perform requested operations

cibadmin --query --local: 107

Signon to CIB failed: Transport endpoint is not connected
Init failed, could not perform requested operations

cibadmin --query --local: 107

Signon to CIB failed: Transport endpoint is not connected
Init failed, could not perform requested operations

cibadmin --query --local: 107

Signon to CIB failed: Transport endpoint is not connected
Init failed, could not perform requested operations

cibadmin --query --local: 107

Signon to CIB failed: Transport endpoint is not connected
Init failed, could not perform requested operations

service corosync status: 0
 corosync.service - Corosync Cluster Engine
   Loaded: loaded (/usr/lib/systemd/system/corosync.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2017-09-05 22:52:36 PDT; 46s ago
     Docs: man:corosync
           man:corosync.conf
           man:corosync_overview
 Main PID: 9808 (corosync)
   CGroup: /system.slice/corosync.service
           9808 corosync

Sep 05 22:52:36 lotus-10vm15 systemd[1]: Starting Corosync Cluster Engine...
Sep 05 22:52:36 lotus-10vm15 systemd[1]: Started Corosync Cluster Engine.
Sep 05 22:52:36 lotus-10vm15 corosync[10029]: Starting Corosync Cluster Engine (corosync): [  OK  ]

Redirecting to /bin/systemctl status corosync.service

service pacemaker status: 0
 pacemaker.service - Pacemaker High Availability Cluster Manager
   Loaded: loaded (/usr/lib/systemd/system/pacemaker.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2017-09-05 22:52:59 PDT; 24s ago
     Docs: man:pacemakerd
           http://clusterlabs.org/doc/en-US/Pacemaker/1.1-pcs/html/Pacemaker_Explained/index.html
 Main PID: 10128 (pacemakerd)
   CGroup: /system.slice/pacemaker.service
           10128 /usr/sbin/pacemakerd -f

Sep 05 22:52:59 lotus-10vm15 systemd[1]: Started Pacemaker High Availability Cluster Manager.
Sep 05 22:52:59 lotus-10vm15 systemd[1]: Starting Pacemaker High Availability Cluster Manager...
Sep 05 22:52:59 lotus-10vm15 pacemakerd[10128]:   notice: Additional logging available in /var/log/pacemaker.log

Redirecting to /bin/systemctl status pacemaker.service


description: ConfigurePacemakerStep: {'host': <ManagedHost: lotus-10vm15.lotus.hpdd.lab.intel.com>}
class_name: ConfigurePacemakerStep
backtrace: Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/chroma_agent/device_plugins/action_runner.py", line 164, in run

  File "/usr/lib/python2.7/site-packages/chroma_agent/plugin_manager.py", line 305, in run

  File "/usr/lib/python2.7/site-packages/chroma_agent/action_plugins/manage_pacemaker.py", line 81, in configure_pacemaker

  File "/usr/lib/python2.7/site-packages/chroma_agent/action_plugins/manage_pacemaker.py", line 96, in _configure_pacemaker

  File "/usr/lib/python2.7/site-packages/chroma_agent/lib/pacemaker.py", line 136, in __init__

  File "/usr/lib/python2.7/site-packages/chroma_agent/lib/pacemaker.py", line 144, in cib_available

  File "/usr/lib/python2.7/site-packages/chroma_agent/lib/pacemaker.py", line 287, in cibadmin

PacemakerError: cibadmin --query --local timed out after 10 seconds: rc: 107, stderr: Signon to CIB failed: Transport endpoint is not connected
Init failed, could not perform requested operations


created_at: 2017-09-06T05:52:50.576459
args: {u'host': u'lotus-10vm15.lotus.hpdd.lab.intel.com'}
modified_at: 2017-09-06T05:53:25.529440
step_index: 1
state: failed
result: 
resource_uri: /api/step/16/
id: 16
log: 


--------------------- >> end captured stdout << ----------------------
```

**Comment by jgrund** [comment]
No longer appears to be issue.
