### ISSUE TITLE
SSHException: Error reading SSH protocol banner debug

### ISSUE THREAD

**Issue by brianjmurrell** [whamcloud/integrated-manager-for-lustre#29]
Every now and then an ssh operation in one of our tests throws an exception such as:

```
Traceback (most recent call last):
File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_lnet_functionality.py", line 15, in setUp
super(TestLNetFunctionality, self).setUp()
File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 137, in setUp
self.reset_cluster()
File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 626, in reset_cluster
self.remote_operations.unmount_clients()
File "/usr/share/chroma-manager/tests/integration/core/remote_operations.py", line 921, in unmount_clients
'mount')
File "/usr/share/chroma-manager/tests/integration/core/remote_operations.py", line 375, in _ssh_address
ssh.connect(address, **args)
File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 338, in connect
t.start_client()
File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 492, in start_client
raise e
SSHException: Error reading SSH protocol banner
```

It would be good to get some idea of why this is happening.

So let's first [gather some diagnostics](https://github.com/intel-hpdd/intel-manager-for-lustre/pull/27) at the time that this is occurring. We might discover that simply trying again will be successful but it would be interesting to see current state before simply assuming
that is the solution.

**Comment by brianjmurrell** [comment]
It's difficult to correlate times exactly due to the lack of time-stamping in the console logs but the few instances of this that I have investigated have [LU-9568](https://jira.hpdd.intel.com/browse/LU-9568) happening on the same node as this failure so this failure is entirely expected if it is happening while [LU-9568](https://jira.hpdd.intel.com/browse/LU-9568) is happening.

**Comment by jgrund** [comment]
Appears to no longer be an issue.
