### ISSUE TITLE
SSI: failure due to pool corruption

### ISSUE THREAD

**Issue by tanabarr** [whamcloud/integrated-manager-for-lustre#645]
http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/5907/arch=x86_64,distro=el7//consoleFull

```
test_creation_conf_params (tests.integration.shared_storage_configuration.test_conf_params.TestConfParams) ... FAIL
FAIL
Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_conf_params.py", line 60, in test_creation_conf_params
    self._create_with_params()
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_conf_params.py", line 36, in _create_with_params
    'conf_params': {'llite.max_cached_mb': '16'}})
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 406, in create_filesystem
    timeout = LONG_TEST_TIMEOUT
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 260, in wait_for_command
    command)
AssertionError: {u'jobs': [u'/api/job/27/', u'/api/job/28/', u'/api/job/29/', u'/api/job/30/', u'/api/job/31/', u'/api/job/32/', u'/api/job/33/', u'/api/job/34/', u'/api/job/35/', u'/api/job/36/', u'/api/job/37/', u'/api/job/38/', u'/api/job/39/', u'/api/job/40/', u'/api/job/41/', u'/api/job/42/', u'/api/job/43/'], u'complete': True, u'created_at': u'2018-06-04T06:37:47.766367', u'message': u'Creating filesystem testfs', u'cancelled': True, u'errored': True, u'resource_uri': u'/api/command/9/', u'id': 9, u'logs': u"\n\n\n\n\n\n\nError (1) running 'zfs list -H -o name -r zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk13': '' 'cannot open 'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk13': pool I/O is currently suspended\n'\n\n\n\n\n\nError (1) running 'zfs list -H -o name -r zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk15': '' 'cannot open 'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk15': pool I/O is currently suspended\n'\n\n\n\n\n\n\n\n\n\n\n\n"}
```

**Comment by jgrund** [comment]
snip of when suspension occurs

```
Jun 03 23:35:58 lotus-49vm15 firewalld[875]: WARNING: ALREADY_ENABLED: '2224:tcp' already in 'public'
Jun 03 23:35:59 lotus-49vm15 firewalld[875]: WARNING: ALREADY_ENABLED: 2224:tcp
Jun 03 23:36:00 lotus-49vm15 systemd[1]: Starting PCS GUI and remote configuration interface...
Jun 03 23:36:01 lotus-49vm15 systemd[1]: Started PCS GUI and remote configuration interface.
Jun 03 23:36:01 lotus-49vm15 kernel: WARNING: MMP writes to pool 'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk15' have not succeeded in over 5s; suspending pool
Jun 03 23:36:01 lotus-49vm15 kernel: WARNING: Pool 'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk15' has encountered an uncorrectable I/O failure and has been suspended.
Jun 03 23:36:01 lotus-49vm15 zed[10838]: eid=547 class=io_failure pool_guid=0x5D7B37B1286DC045
Jun 03 23:36:01 lotus-49vm15 kernel: WARNING: MMP writes to pool 'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk13' have not succeeded in over 5s; suspending pool
Jun 03 23:36:01 lotus-49vm15 kernel: WARNING: Pool 'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk13' has encountered an uncorrectable I/O failure and has been suspended.
Jun 03 23:36:01 lotus-49vm15 zed[10840]: eid=548 class=io_failure pool_guid=0x8E81E66C32BE8537
Jun 03 23:36:01 lotus-49vm15 kernel: WARNING: MMP writes to pool 'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11' have not succeeded in over 5s; suspending pool
Jun 03 23:36:01 lotus-49vm15 kernel: WARNING: Pool 'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk11' has encountered an uncorrectable I/O failure and has been suspended.
Jun 03 23:36:01 lotus-49vm15 zed[10842]: eid=549 class=io_failure pool_guid=0x2179711E91B4BF57
```

**Comment by jgrund** [comment]
This looks like: https://jira.hpdd.intel.com/browse/LU-9845

**Comment by utopiabound** [comment]
Can you try adding the following?  This should both decrease the likely hood of failure (at the cost of slightly longer import times), and save a history to see where it failed to write if it does fail.
{noformat}
options zfs zfs_multihost_history=100
options zfs zfs_multihost_fail_intervals=20
{noformat}

**Comment by jgrund** [comment]
<img width="1858" alt="screen shot 2018-06-06 at 11 18 20 am" src="https://user-images.githubusercontent.com/458717/41047995-c6c84778-697b-11e8-8b63-d410bec8037e.png">

Here are the commands / alerts / events that occurred leading up to this failure.

What seems odd to me is creating a fs was started one second before the `HostOfflineAlert` was lowered. Wonder if we are not waiting for hosts to come online before scheduling a fs create.

**Comment by jgrund** [comment]
@utopiabound, yes will look at adding those in
