### ISSUE TITLE
Multiple volume nodes reported in API per volume + server

### ISSUE THREAD

**Issue by tanabarr** [whamcloud/integrated-manager-for-lustre#652]
Multiple items for the same host / volume pair are reported for a single volume via the API:

![dup_volume_nodes](https://user-images.githubusercontent.com/3277648/41423091-5144265c-6ff2-11e8-9123-5a6ade2d5c93.png)

Looking in the database we can see that of given volume nodes that appear repeated (host_id 9 == kapollo2), only one of them is `not_deleted`. We can therefore surmise that the UI is reporting deleted elements and it's not being misrepresented in the resource manager.

```
chroma=> select * from chroma_core_volumenode where host_id=9 and path='/dev/disk/by-id/scsi-35000c50088ed1efb';
  id  | volume_id | host_id |                  path                  | storage_resource_id | primary | use | not_deleted
------+-----------+---------+----------------------------------------+---------------------+---------+-----+-------------
 1626 |       344 |       9 | /dev/disk/by-id/scsi-35000c50088ed1efb |                     | f       | t   |
 2140 |       344 |       9 | /dev/disk/by-id/scsi-35000c50088ed1efb |                3044 | t       | t   | t
 1899 |       344 |       9 | /dev/disk/by-id/scsi-35000c50088ed1efb |                     | t       | t   |
(3 rows)

chroma=> select * from chroma_core_volumenode where host_id=8 and path='/dev/disk/by-id/scsi-35000c50088ed1efb';
  id  | volume_id | host_id |                  path                  | storage_resource_id | primary | use | not_deleted
------+-----------+---------+----------------------------------------+---------------------+---------+-----+-------------
 1340 |       344 |       8 | /dev/disk/by-id/scsi-35000c50088ed1efb |                     | t       | t   |
 1700 |       344 |       8 | /dev/disk/by-id/scsi-35000c50088ed1efb |                1882 | f       | f   | t
(2 rows)
```

**Comment by tanabarr** [comment]
API call:
![image](https://user-images.githubusercontent.com/3277648/41429806-16056088-7006-11e8-953b-fff608a2e186.png)

**Comment by jgrund** [comment]
So, the root cause here is there are multiple volume nodes being presented as choices for a single host.

This was previously normalized (guessing this a regression in the resource_manager) so that there was at most one path per host usable.

**Comment by johnsonw** [comment]
From plugin-runner.log
```
[2018-06-14 15:43:42,604: ERROR/agent_daemon] Exception in agent session for linux from kapollo02: Traceback (most recent call last):

  File "/usr/share/chroma-manager/chroma_core/services/plugin_runner/agent_daemon.py", line 171, in on_message
    session.plugin.do_agent_session_continue(message['body'])

  File "/usr/share/chroma-manager/chroma_core/lib/storage_plugin/base_plugin.py", line 135, in do_agent_session_continue
    self._update(self.agent_session_continue, self._root_resource.host_id, data)

  File "/usr/share/chroma-manager/chroma_core/lib/storage_plugin/base_plugin.py", line 212, in _update
    fn(*args)

  File "/usr/share/chroma-manager/chroma_core/plugins/linux.py", line 193, in agent_session_continue
    self.agent_session_start(host_id, None, initial_scan=False)

  File "/usr/share/chroma-manager/chroma_core/plugins/linux.py", line 201, in agent_session_start
    devices = get_devices(fqdn)

  File "/usr/share/chroma-manager/chroma_core/plugins/block_devices.py", line 25, in get_devices
    _data = fetch_aggregator()

  File "/usr/share/chroma-manager/chroma_core/plugins/block_devices.py", line 21, in fetch_aggregator
    return json.loads(payload)

  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)

  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")

ValueError: No JSON object could be decoded
``

**Comment by tanabarr** [comment]
that exception shouldn't be occurring with https://github.com/intel-hpdd/intel-manager-for-lustre/pull/616/files
what commit on master is it from?

**Comment by tanabarr** [comment]
As @joegrund points out, we are seeing multiple volume nodes for different path to the same volume. It's the output of the aggregator that we need to be monitoring, because if the ndt is not being used to resolve paths then we will have multiple volumenodes for the same volume/host combinations in a multipath setup

**Comment by jgrund** [comment]
Update: I added mpath support to our vagrant boxes and tried to reproduce this. Interestingly I don't see the same issue:

![screen shot 2018-07-02 at 11 02 45 am](https://user-images.githubusercontent.com/458717/42171613-b41679c6-7de7-11e8-8e83-f864e6111981.png)

**Comment by jgrund** [comment]
Looking again at the old output, there is not even any top-level `mpaths` keys from the aggregator. 

I think this is fixed.
