### ISSUE TITLE
paramiko.transport: ERROR: Socket exception: Connection reset by peer (104)

### ISSUE THREAD

**Issue by brianjmurrell** [whamcloud/integrated-manager-for-lustre#72]
We sometimes get failures in running tests such as:

```
test_toggled_outlet_does_not_trigger_fencing_update (tests.integration.shared_storage_configuration.test_power_control.TestHostFencingConfig) ... ERROR
ERROR
Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 193, in tearDown
    "==== stopping test %s =====" % self)
  File "/usr/share/chroma-manager/tests/integration/core/remote_operations.py", line 515, in inject_log_message
    self._ssh_fqdn(fqdn, "logger \"%s\"" % message)
  File "/usr/share/chroma-manager/tests/integration/core/remote_operations.py", line 467, in _ssh_fqdn
    return self._ssh_address(address, command, expected_return_code, timeout, buffer)
  File "/usr/share/chroma-manager/tests/integration/core/remote_operations.py", line 436, in _ssh_address
    channel.exec_command(command)
  File "/usr/lib/python2.7/site-packages/paramiko/channel.py", line 60, in _check
    return func(self, *args, **kwds)
  File "/usr/lib/python2.7/site-packages/paramiko/channel.py", line 234, in exec_command
    self._wait_for_event()
  File "/usr/lib/python2.7/site-packages/paramiko/channel.py", line 1103, in _wait_for_event
    raise e
error: [Errno 104] Connection reset by peer
```

Where the _Connection reset_ is coming from:

```
test: INFO: SSH address = lotus-56vm5.lotus.hpdd.lab.intel.com, args = {'username': 'root'}
paramiko.transport: ERROR: Socket exception: Connection reset by peer (104)
```

It would be nice to get some diagnostics about the host to which the connection was that got reset.

**Comment by brianjmurrell** [comment]
[Another](http://jenkins.lotus.hpdd.lab.intel.com/job/integration-tests-shared-storage-configuration/arch=x86_64,distro=el7/1147):

```
test_off_on_operations (tests.integration.shared_storage_configuration.test_power_control.TestPduOperations) ... ERROR
ERROR
Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_power_control.py", line 16, in setUp
    super(ChromaPowerControlTestCase, self).setUp()
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 134, in setUp
    "=====" % self)
  File "/usr/share/chroma-manager/tests/integration/core/remote_operations.py", line 537, in inject_log_message
    self._ssh_fqdn(fqdn, "logger \"%s\"" % message)
  File "/usr/share/chroma-manager/tests/integration/core/remote_operations.py", line 489, in _ssh_fqdn
    return self._ssh_address(address, command, expected_return_code, timeout, buffer)
  File "/usr/share/chroma-manager/tests/integration/core/remote_operations.py", line 442, in _ssh_address
    ssh.connect(address, **args)
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 338, in connect
    t.start_client()
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 492, in start_client
    raise e
error: [Errno 104] Connection reset by peer
```

**Comment by jgrund** [comment]
No longer appears to be issue.
