### ISSUE TITLE
Fix SSI test_api_rejects_multi_cluster_failover

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#721]
tests.integration.shared_storage_configuration.test_ha_clustering.TestHaClusterVolumes.test_api_rejects_multi_cluster_failover 

Is consistently failing.

We need to fix this so we can get through a full test run

**Comment by jgrund** [comment]
Related Traceback:

```
[2018-08-29 02:04:55,257: ERROR/django.request.tastypie] Internal Server Error: /api/volume/2/
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tastypie/resources.py", line 217, in wrapper
    response = callback(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tastypie/resources.py", line 468, in dispatch_detail
    return self.dispatch('detail', request, **kwargs)
  File "/usr/lib/python2.7/site-packages/tastypie/resources.py", line 491, in dispatch
    response = method(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/tastypie/resources.py", line 1453, in put_detail
    updated_bundle = self.obj_update(bundle=bundle, **self.remove_api_resource_names(kwargs))
  File "/usr/share/chroma-manager/chroma_api/validation_utils.py", line 31, in _validate
    return fn(self, bundle, **kwargs)
  File "/usr/share/chroma-manager/chroma_api/volume.py", line 203, in obj_update
    raise AssertionError("Volume %s is in use!" % volume['id'])
AssertionError: Volume 2 is in use!
```
