### ISSUE TITLE
How to build iml on centos6.5 ?

### ISSUE THREAD

**Issue by iskylite** [whamcloud/integrated-manager-for-lustre#728]
### Description 
(I am a beginner from china，so poor English， please)

I need to build iml on centos6.5, but I failed! so please help me how to build iml on centos6?

Below are two failed Build logs;

*   one is build iml-2.3.0.0 on centos6.5, I think the iml-2.3.0.0 source code missing some files,Maybe my false.

*   another is build iml-4.0.0.0 on centos6.5

#### Build iml-2.3.0.0 On Centos6
```
 [[ /usr/lib/python2.6/site-packages/chroma_agent/chroma_common/lib/evaluator.pyc == /etc/init/tty.conf ]]
+ echo '/usr/lib/python2.6/site-packages/chroma_agent/chroma_common/lib/evaluator.py[c,o]'
+ /usr/lib/rpm/find-debuginfo.sh --strict-build-id /root/iml/iml-2.3/chroma-agent/_topdir/BUILD/chroma-agent-2.3.0.0
find: `debug': No such file or directory
+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/redhat/brp-compress
+ /usr/lib/rpm/redhat/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/redhat/brp-strip-comment-note /usr/bin/strip /usr/bin/objdump
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python
Bytecompiling .py files below /root/iml/iml-2.3/chroma-agent/_topdir/BUILDROOT/chroma-agent-2.3.0.0-4240.x86_64/usr/lib/python2.6 using /usr/bin/python2.6
+ /usr/lib/rpm/redhat/brp-python-hardlink
+ /usr/lib/rpm/redhat/brp-java-repack-jars
Processing files: chroma-agent-2.3.0.0-4240.noarch
Requires(interp): /bin/sh
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PartialHardlinkSets) <= 4.0.4-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Requires(post): /bin/sh selinux-policy
Requires: /usr/bin/python python(abi) = 2.6
Processing files: chroma-agent-management-2.3.0.0-4240.noarch
Requires(interp): /bin/sh /bin/sh /bin/sh
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PartialHardlinkSets) <= 4.0.4-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1 rpmlib(VersionedDependencies) <= 3.0.3-1
Requires(post): /bin/sh
Requires(postun): /bin/sh
Requires: /bin/sh /usr/bin/python python(abi) = 2.6
Conflicts: sysklogd
Obsoletes: pacemaker-iml <= 1.1.7-6.wc2.el6 pacemaker-iml-cluster-libs <= 1.1.7-6.wc2.el6 pacemaker-iml-libs <= 1.1.7-6.wc2.el6 pacemaker-iml-cli <= 1.1.7-6.wc2.el6
Processing files: chroma-agent-devel-2.3.0.0-4240.noarch
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Requires: python(abi) = 2.6
Checking for unpackaged file(s): /usr/lib/rpm/check-files /root/iml/iml-2.3/chroma-agent/_topdir/BUILDROOT/chroma-agent-2.3.0.0-4240.x86_64
Wrote: /root/iml/iml-2.3/chroma-agent/_topdir/RPMS/noarch/chroma-agent-2.3.0.0-4240.noarch.rpm
Wrote: /root/iml/iml-2.3/chroma-agent/_topdir/RPMS/noarch/chroma-agent-management-2.3.0.0-4240.noarch.rpm
Wrote: /root/iml/iml-2.3/chroma-agent/_topdir/RPMS/noarch/chroma-agent-devel-2.3.0.0-4240.noarch.rpm
Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.cHTux6
+ umask 022
+ cd /root/iml/iml-2.3/chroma-agent/_topdir/BUILD
+ cd chroma-agent-2.3.0.0
+ rm -rf /root/iml/iml-2.3/chroma-agent/_topdir/BUILDROOT/chroma-agent-2.3.0.0-4240.x86_64
+ exit 0
mv _topdir/RPMS/noarch/chroma-agent-*.noarch.rpm dist/
rm -rf _topdir
make[1]: Leaving directory `/root/iml/iml-2.3/chroma-agent'
set -e; \
	if true; then \
		make -C chroma-manager all; \
		if [ all != download -a -d chroma-manager/dist/ ]; then \
			cp -a chroma-manager/dist/* dist/; \
		fi; \
	fi
+ sed -e 's/^v//' -e 's/RC[0-9]*//'
+ git describe --match 'v[0-9]*'
warning: tag 'v2.3.0.0RC4' is really 'v2.3.0.0' here
make[1]: Entering directory `/root/iml/iml-2.3/chroma-manager'
rm -rf  dist
mkdir dist
echo 'VERSION = "2.3.0.0"' > scm_version.py
echo 'PACKAGE_VERSION = "2.3.0.0"' >> scm_version.py
echo 'BUILD = "4240"' >> scm_version.py
echo 'IS_RELEASE = True' >> scm_version.py
Setting up ziplocker module for development...

cp:  can't state "../../../../chroma-externals/ziplocker/node_modules/" : No such file or directory
make[1]: *** [ziplocker/node_modules] Error 1
make[1]: Leaving directory `/root/iml/iml-2.3/chroma-manager'
make: *** [chroma-manager] Error 2
```

#### Build iml-4.0.0.0 On Centos6 

I have tried to build iml-4.0.0.0 on centos6 ,but I failed!
this is the failed log. Maybe npm repository lost and missed some files.
```
npm info using npm@1.3.6
npm info using node@v0.10.48
npm info preinstall ui-modules@4.0.0
npm info trying registry request attempt 1 at 22:19:57
npm http GET https://registry.npmjs.org/iml/realtime/6.0.0
npm info trying registry request attempt 1 at 22:19:57
npm http GET https://registry.npmjs.org/iml/view-server/6.4.0
npm info trying registry request attempt 1 at 22:19:57
npm http GET https://registry.npmjs.org/iml/old-gui/2.1.2
npm info trying registry request attempt 1 at 22:19:57
npm http GET https://registry.npmjs.org/iml/socket-worker/3.2.0
npm http 404 https://registry.npmjs.org/iml/realtime/6.0.0
npm ERR! Error: No dist in undefined package
npm ERR!     at next (/usr/lib/node_modules/npm/lib/cache.js:746:26)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache.js:739:5
npm ERR!     at saved (/usr/lib/node_modules/npm-registry-client/lib/get.js:148:7)
npm ERR!     at /usr/lib/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-431.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "i" "-d"
npm ERR! cwd /root/iml/integrated-manager-for-lustre/chroma-manager/ui-modules
npm ERR! node -v v0.10.48
npm ERR! npm -v 1.3.6
npm http 404 https://registry.npmjs.org/iml/old-gui/2.1.2
npm http 404 https://registry.npmjs.org/iml/view-server/6.4.0
npm http 404 https://registry.npmjs.org/iml/socket-worker/3.2.0
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/iml/integrated-manager-for-lustre/chroma-manager/ui-modules/npm-debug.log
npm ERR! not ok code 0
make[1]: *** [ui-modules] Error 1
make[1]: Leaving directory `/root/iml/integrated-manager-for-lustre/chroma-manager'
make: *** [chroma-manager] Error 2
```

**Comment by jgrund** [comment]
Hi @iskylite,

You should try to build latest IML 4.0.7 using CentOS 7.5.

Use these instructions to build:

```
yum install -y yum-plugin-copr make git epel-release python-setuptools rpm-build ed python-virtualenv systemd-devel graphviz-devel createrepo;

yum group install -y "Development Tools";

yum copr enable managerforlustre/manager-for-lustre -y;

yum copr enable ngompa/dnf-el7 -y;

yum install -y nodejs npm dnf 'dnf-command(repoquery)' ruby libpqxx-devel;

export distro=${distro:-el7}

cd integrated-manager-for-lustre/

scripts/jenkins_build
```

**Comment by iskylite** [comment]
thx， @jgrund 
Thanks for you help, but I need to build IML using CentOS6.5 or just have a iml-<version>.tar.gz to be installed on CentOS6.5 . Because  the cluster that I have managed is running CentOS6.5 .

So , I need a tar ball having been built for CentOS 6.5 , the way to build IML using CentOS6.5 .

Please.

**Comment by iskylite** [comment]
hi， @jgrund 
I'm asking you to help me building IML using CentOS6.5. Or do you have a tar ball like iml-4.0.7.0.tar.gz to intsall iml software on CentOS6.5 , I need it ,please.

**Comment by iskylite** [comment]
sorry, @johnsonw , I just get your reply.
I can't upgrade the operating system from 6.5 to 7.5? There are many software dependent operating systems OS 6.5. In fact, I don't need many new features. I just need the older IML software to monitor the lustre file system. So I need to build iml using CentOS6.5 , or do you have the older iml install package  for CentOS6.5.
