### ISSUE TITLE
Some OSTs are not being discovered during installation of IML

### ISSUE THREAD

**Issue by markbouza** [whamcloud/integrated-manager-for-lustre#735]
### Description 

Some of our OSTs are not being located during the IML installation process.

Each of our eight OSS servers have five OSTs, for a total of 40 OSTs. 

We have two OSS servers where none of their OSTs are discovered.

### Repro

We've tried:

1. Complete tear-down and re-installation of IML. 

We originally had three OSS servers where none of their OSTs were discovered. During the re-installation, one of the originally missing OSS servers had it's OSTs discovered and added successfully.

2. Remove and re-add of the two problematic OSS servers.

This threw the same "AssertionError" error in the plugin_runner.log file.

### Version

What version of IML? 

iml-gui-6.4.0-827.1.el7.noarch
python2-iml-manager-cli-4.1.0.0-5131.30.g054a091.el7.noarch
iml-old-gui-3.0.0-40.el7.noarch
iml-update-handler-1.0.0-24.12.gb359059.el7.noarch
iml_sos_plugin-2.2.2-1.el7.noarch
python2-iml-manager-4.1.0.0-5131.30.g054a091.el7.noarch
python2-iml-manager-libs-4.1.0.0-5131.30.g054a091.el7.noarch
iml-view-server-8.0.2-142.el7.noarch
iml-realtime-7.0.0-85.el7.x86_64
iml-socket-worker-4.0.0-98.el7.noarch
iml-online-help-2.5.1-1.el7.noarch
python2-iml-common1.4-1.4.4-43.2.el7.noarch
iml-device-scanner-aggregator-2.2.0-198.el7.x86_64
iml-srcmap-reverse-3.0.7-1.el7.noarch

What Operating System?
What Operating System version?

$ cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)
$ uname -a
Linux exaiml 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### iml-diagnostics

Attached as [sosreport-exaiml-20181017092030.tar.xz.gz](https://github.com/whamcloud/integrated-manager-for-lustre/files/2488405/sosreport-exaiml-20181017092030.tar.xz.gz)

**Comment by markbouza** [comment]
Figured we could add a little more background which may be helpful. Our site originally ran the IEEL 2.3.0.0 version of lustre. We used the version of IML bundled with this software to create a HA setup enabled between our MDS and MGS. Our OSS servers are ZFS-backed, so we left those out of the HA setup and created the OSTs by hand. Support for ZFS-backed OSSes in HA configuration was not supported in this earlier version of IML.

We've recently upgraded our Lustre file system to 2.10.5-1 on our MDS, MGS and OSSes. Instead of a nuke and re-pave, we were directed to try and upgrade the file system while saving the existing data in lustre. This we were able to do.

So now we are trying to get all of our lustre servers as "monitored storage servers" into this new version of IML. The MDS and MGS are no longer added as "managed storage servers".

I do notice the following errors in the plugin_runner.log on our new IML server when using "Add Server" on our two "problematic" OSS servers:

`[2018-10-17 16:07:34,518: ERROR/rpc] RunOneRpc: exception calling setup_host: Traceback (most recent call last):

  File "/usr/share/chroma-manager/chroma_core/services/rpc.py", line 125, in run
    'result': self.rpc._local_call(self.body['method'], *self.body['args'], **self.body['kwargs']),

  File "/usr/share/chroma-manager/chroma_core/services/rpc.py", line 629, in _local_call
    return fn(*args, **kwargs)

  File "/usr/share/chroma-manager/chroma_core/services/plugin_runner/__init__.py", line 23, in setup_host
    self.handlers[plugin_name].setup_host(host_id, data)

  File "/usr/lib/python2.7/site-packages/django/db/transaction.py", line 224, in inner
    return func(*args, **kwargs)

  File "/usr/share/chroma-manager/chroma_core/services/plugin_runner/agent_daemon.py", line 89, in setup_host
    assert(session is not None)

AssertionError
`

**Comment by markbouza** [comment]
There are two other issues we have noticed, that perhaps are related?

1) IML dashboard is using IDs instead of OST names in the Read/Write Heat Map and OST Balance graphs

The older version was able to use the OST names. Is there method or conf file that we can use to have IML use the OST names instead?

2) All the OSTs are flagged as Offline

Each of our OSTs have errors associated with them; e.g.

`
Errror	TargetOfflineAlert	2018-10-16 16:35:45		Target lustre1-OST0000 offline
Errror	TargetOfflineAlert	2018-10-16 16:35:45		Target lustre1-OST0001 offline
...
Errror	TargetOfflineAlert	2018-10-16 16:35:45		Target lustre1-OST001d offline
`
