### ISSUE TITLE
Unexpected UpdatesAvailableAlerts

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#744]
Seen in:

https://build.whamcloud.com/view/IML/job/integration-tests-shared-storage-configuration/687/

```
Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_alerting.py", line 105, in test_alerts
    active=True)
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 324, in wait_alerts
    raise AssertionError(alerts)
AssertionError: [u'TargetOfflineAlert', u'TargetOfflineAlert', u'TargetOfflineAlert', u'TargetOfflineAlert', u'UpdatesAvailableAlert', u'UpdatesAvailableAlert', u'UpdatesAvailableAlert', u'UpdatesAvailableAlert']
```

iml-update-check is reporting the following packages are available for update:

```
[<hawkey.Package object id 17653, kernel-tools-3.10.0-862.9.1.el7_lustre.x86_64, lustre>, 
<hawkey.Package object id 17655, kernel-tools-libs-3.10.0-862.9.1.el7_lustre.x86_64, lustre>, 
<hawkey.Package object id 17678, python-perf-3.10.0-862.9.1.el7_lustre.x86_64, lustre>]
```

These versions may be superior to what's currently installed, but they were not directly pinned in any Lustre specs or they would have been pulled in.

There is also the issue that iml-update-check filters to whatever is in `/etc/yum.repos.d/Intel-Lustre-Agent.repo`, but this may be at odds with what is supplied in a given server profile.

**Comment by jgrund** [comment]
This is fixed in an upstream Lustre repo packaging change. However the fixes we need on the IML side are in https://github.com/whamcloud/iml-update-check/issues/11 and https://github.com/whamcloud/iml-update-check/issues/12
