### ISSUE TITLE
IML 4.0.9.1 Testing Results

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#797]

**Comment by utopiabound** [comment]
Upgrade of database failed with following:
```
[root@ieel-mgr1 ~]# chroma-config setup -v
Starting setup...

DB already accessible
Creating database tables...
Syncing...
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)
Migrating...
Running migrations for tastypie:
 - Migrating forwards to 0002_add_apikey_index.
 > tastypie:0002_add_apikey_index
 - Loading initial data for tastypie.
Installed 0 object(s) from 0 fixture(s)
Running migrations for chroma_core:
 - Migrating forwards to 0040_table_update_notify.
 > chroma_core:0020_auto__add_field_userprofile__gui_config
 > chroma_core:0021_auto__add_installhostpackagesjob__add_unconfigurelnetjob__add_setupmon
 > chroma_core:0022_auto__add_field_nid_lnd_type
 > chroma_core:0023_auto__add_unconfigurersyslogjob__add_getcorosyncstatejob__add_pacemake
 > chroma_core:0024_auto__del_event__add_commandalert__add_getlnetstatejob__del_field_aler
 > chroma_core:0025_auto__add_field_serverprofile_rsyslog__add_field_serverprofile_ntp__ad
 > chroma_core:0026_auto__add_unconfigurecorosync2job__add_startcorosync2job__add_configur
 > chroma_core:0027_auto__del_setupworkertjob__del_removehostjob__add_setupworkerjob__add_
 > chroma_core:0028_auto__add_field_alertevent__message__add_field_ipmibmcunavailablealert
 > chroma_core:0029_auto__add_triggerpluginupdatesjob
 > chroma_core:0030_auto__add_field_volume_usable_for_lustre
 > chroma_core:0031_auto__add_stonithnotenabledalert
 > chroma_core:0032_remove_unused_tables
 > chroma_core:0033_health_status_procedure
 > chroma_core:0034_api_key_procedure
 > chroma_core:0035_auto__del_userprofile
 > chroma_core:0036_auto__del_unconfigurersyslogjob__del_rsyslogconfiguration__del_configu
 > chroma_core:0037_remove_rsyslog_types
 > chroma_core:0038_del_command_dismissed
 > chroma_core:0039_add_primary_umtm_stepresults
Error in migration: chroma_core:0039_add_primary_umtm_stepresults
Traceback (most recent call last):
  File "/usr/bin/chroma-config", line 10, in <module>
    load_entry_point('chroma-manager==4.0.9.1', 'console_scripts', 'chroma-config')()
  File "/usr/share/chroma-manager/chroma_core/lib/service_config.py", line 857, in chroma_config
    errors = service_config.setup(username, password, ntpserver, check_db_space)
  File "/usr/share/chroma-manager/chroma_core/lib/service_config.py", line 583, in setup
    error = self._setup_database(username, password, check_db_space)
  File "/usr/share/chroma-manager/chroma_core/lib/service_config.py", line 521, in _setup_database
    self._syncdb()
  File "/usr/share/chroma-manager/chroma_core/lib/service_config.py", line 503, in _syncdb
    ManagementUtility(args).execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/usr/lib/python2.7/site-packages/south/management/commands/syncdb.py", line 103, in handle_noargs
    management.call_command('migrate', **options)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/usr/lib/python2.7/site-packages/south/migration/__init__.py", line 220, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/usr/lib/python2.7/site-packages/south/migration/migrators.py", line 256, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/usr/lib/python2.7/site-packages/south/migration/migrators.py", line 331, in migrate_many
    result = self.migrate(migration, database)
  File "/usr/lib/python2.7/site-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration, database)
  File "/usr/lib/python2.7/site-packages/south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "/usr/lib/python2.7/site-packages/south/migration/migrators.py", line 84, in run_migration
    migration_function()
  File "/usr/lib/python2.7/site-packages/south/migration/migrators.py", line 60, in <lambda>
    return (lambda: direction(orm))
  File "/usr/share/chroma-manager/chroma_core/south_migrations/0039_add_primary_umtm_stepresults.py", line 9, in forwards
    if obj.step_klass.__name__ == 'UpdateManagedTargetMount' \
AttributeError: 'unicode' object has no attribute '__name__'

```

**Comment by utopiabound** [comment]
IML 4.0.9.1rc2 upgrade from 2.4.2.7: **SUCCESS**

**Comment by jgrund** [comment]
Closing this out with above upgrade check.
