### ISSUE TITLE
Upgrade EE 2.4.2.7 to IML 4.0.9.1 to IML 5 fails during migration

### ISSUE THREAD

**Issue by utopiabound** [whamcloud/integrated-manager-for-lustre#803]
### Description 

`chroma-config setup` fails during migration phase.

### Repro

This system is an upgrade from EE 2.4.2.7 to IML 4.0.9.1 to IML 5

### Version

IML 5 (lustre-2-12 branch)
el7.6

### Diagnostics
```
# chroma-config setup -v
Starting setup...

DB already accessible
Creating database tables...
Syncing...
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)
Migrating...
Traceback (most recent call last):
  File "/usr/bin/chroma-config", line 10, in <module>
    load_entry_point('iml-manager==4.1.0.0', 'console_scripts', 'chroma-config')()
  File "/usr/share/chroma-manager/chroma_core/lib/service_config.py", line 941, in chroma_config
    errors = service_config.setup(username, password, ntpserver, check_db_space)
  File "/usr/share/chroma-manager/chroma_core/lib/service_config.py", line 660, in setup
    error = self._setup_database(check_db_space)
  File "/usr/share/chroma-manager/chroma_core/lib/service_config.py", line 542, in _setup_database
    self._syncdb()
  File "/usr/share/chroma-manager/chroma_core/lib/service_config.py", line 524, in _syncdb
    ManagementUtility(args).execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/usr/lib/python2.7/site-packages/south/management/commands/syncdb.py", line 103, in handle_noargs
    management.call_command('migrate', **options)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/usr/lib/python2.7/site-packages/south/migration/__init__.py", line 200, in migrate_app
    applied_all = check_migration_histories(applied_all, delete_ghosts, ignore_ghosts)
  File "/usr/lib/python2.7/site-packages/south/migration/__init__.py", line 95, in check_migration_histories
    raise exceptions.GhostMigrations(ghosts)
south.exceptions.GhostMigrations: 

 ! These migrations are in the database but not on disk:
    <chroma_core: 0040_table_update_notify>
 ! I'm not trusting myself; either fix this yourself by fiddling
 ! with the south_migrationhistory table, or pass --delete-ghost-migrations
 ! to South to have it delete ALL of these records (this may not be good).
```
Re-running produces same error.

Possibly related to pull #798 ?

**Comment by jgrund** [comment]
We *really* need to get this re-enabled first: 

https://github.com/whamcloud/integrated-manager-for-lustre/issues/717

**Comment by jgrund** [comment]
In IML 4.0.9.1:

https://github.com/whamcloud/integrated-manager-for-lustre/blob/aa49ac50bd23e519d279e03095fe738df6b2ea45/chroma-manager/chroma_core/south_migrations/0040_table_update_notify.py

In IML 5:

https://github.com/whamcloud/integrated-manager-for-lustre/blob/065d63abae47bbd43488d7984dde38be246049f1/chroma_core/south_migrations/0041_table_update_notify.py

The migrations have shifted between 4 and 5; they are no longer consistent.

We need to get upgrade testing running again so we don't find out about these during dev upgrade.
