### ISSUE TITLE
Metrics not displaying for filesystem when hsm is enabled

### ISSUE THREAD

**Issue by johnsonw** [whamcloud/integrated-manager-for-lustre#850]
### Description 

When creating a filesystem, the filesystem detail page and dashboard should display metrics about the filesystem, like the following:

![image](https://user-images.githubusercontent.com/1100657/55436914-8c95cd00-556b-11e9-9093-c8f5a050066f.png)

![image](https://user-images.githubusercontent.com/1100657/55436924-961f3500-556b-11e9-8ce5-3f486245367f.png)

![image](https://user-images.githubusercontent.com/1100657/55436941-9fa89d00-556b-11e9-9be4-58906a19a334.png)

However, when a filesystem is created with the "Enable HSM" checkbox selected, the graphs do not display at all. Furthermore, it does not display how many clients are connected:

![image](https://user-images.githubusercontent.com/1100657/55437328-9ec43b00-556c-11e9-9f37-b89492a7c0b5.png)

![image](https://user-images.githubusercontent.com/1100657/55437345-a8e63980-556c-11e9-8b20-f5f43dbadda0.png)

![image](https://user-images.githubusercontent.com/1100657/55437364-b69bbf00-556c-11e9-9597-89270c3c9928.png)

 
### Repro

Select the "Enable HSM" checkbox when creating a filesystem.

### Version

What version of IML? latest master
What Operating System? CentOS
What Operating System version? EL 7.6

### Possibly helpful stacktraces:
```
 [2019-04-02 21:04:47,590: ERROR/chroma_core.services.lustre_audit] Error handling lustre message: Traceback (most recent call last):
lustre-audit_1       | 
lustre-audit_1       |   File "/usr/share/chroma-manager/chroma_core/services/lustre_audit/__init__.py", line 32, in on_data
lustre-audit_1       |     UpdateScan().run(host.id, data)
lustre-audit_1       | 
lustre-audit_1       |   File "/usr/share/chroma-manager/chroma_core/services/lustre_audit/update_scan.py", line 60, in run
lustre-audit_1       |     self.audit_host()
lustre-audit_1       | 
lustre-audit_1       |   File "/usr/share/chroma-manager/chroma_core/services/lustre_audit/update_scan.py", line 48, in audit_host
lustre-audit_1       |     self.update_resource_locations()
lustre-audit_1       | 
lustre-audit_1       |   File "/usr/share/chroma-manager/chroma_core/services/lustre_audit/update_scan.py", line 283, in update_resource_locations
lustre-audit_1       |     ["mounted", "unmounted"],
lustre-audit_1       | 
lustre-audit_1       |   File "/usr/share/chroma-manager/chroma_core/services/job_scheduler/job_scheduler_notify.py", line 81, in notify
lustre-audit_1       |     "from_states": from_states,
lustre-audit_1       | 
lustre-audit_1       |   File "/usr/share/chroma-manager/chroma_core/services/queue.py", line 43, in put
lustre-audit_1       |     self.name, serializer="json", exchange_opts={"durable": False}, queue_opts={"durable": False}
lustre-audit_1       | 
lustre-audit_1       |   File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 692, in SimpleQueue
lustre-audit_1       |     exchange_opts, **kwargs)
lustre-audit_1       | 
lustre-audit_1       |   File "/usr/lib/python2.7/site-packages/kombu/simple.py", line 125, in __init__
lustre-audit_1       |     compression=compression)
lustre-audit_1       | 
lustre-audit_1       |   File "/usr/lib/python2.7/site-packages/kombu/messaging.py", line 85, in __init__
lustre-audit_1       |     self.revive(self._channel)
lustre-audit_1       | 
lustre-audit_1       |   File "/usr/lib/python2.7/site-packages/kombu/messaging.py", line 222, in revive
lustre-audit_1       |     self.declare()
lustre-audit_1       | 
lustre-audit_1       |   File "/usr/lib/python2.7/site-packages/kombu/messaging.py", line 105, in declare
lustre-audit_1       |     self.exchange.declare()
lustre-audit_1       | 
lustre-audit_1       |   File "/usr/lib/python2.7/site-packages/kombu/entity.py", line 171, in declare
lustre-audit_1       |     return self.channel.exchange_declare(
lustre-audit_1       | 
lustre-audit_1       |   File "/usr/lib/python2.7/site-packages/kombu/abstract.py", line 118, in channel
lustre-audit_1       |     channel = self._channel = channel()
lustre-audit_1       | 
lustre-audit_1       |   File "/usr/lib/python2.7/site-packages/kombu/utils/__init__.py", line 425, in __call__
lustre-audit_1       |     value = self.__value__ = self.__contract__()
lustre-audit_1       | 
lustre-audit_1       |   File "/usr/lib/python2.7/site-packages/kombu/messaging.py", line 209, in <lambda>
lustre-audit_1       |     channel = ChannelPromise(lambda: connection.default_channel)
lustre-audit_1       | 
lustre-audit_1       |   File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 771, in default_channel
lustre-audit_1       |     self.connection
lustre-audit_1       | 
lustre-audit_1       |   File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 756, in connection
lustre-audit_1       |     self._connection = self._establish_connection()
lustre-audit_1       | 
lustre-audit_1       |   File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 711, in _establish_connection
lustre-audit_1       |     conn = self.transport.establish_connection()
lustre-audit_1       | 
lustre-audit_1       |   File "/usr/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 116, in establish_connection
lustre-audit_1       |     conn = self.Connection(**opts)
lustre-audit_1       | 
lustre-audit_1       |   File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 174, in __init__
lustre-audit_1       |     self._x_start_ok(d, login_method, login_response, locale)
lustre-audit_1       | 
lustre-audit_1       |   File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 820, in _x_start_ok
lustre-audit_1       |     self._send_method((10, 11), args)
lustre-audit_1       | 
lustre-audit_1       |   File "/usr/lib/python2.7/site-packages/amqp/abstract_channel.py", line 56, in _send_method
lustre-audit_1       |     self.channel_id, method_sig, args, content,
lustre-audit_1       | 
lustre-audit_1       |   File "/usr/lib/python2.7/site-packages/amqp/method_framing.py", line 221, in write_method
lustre-audit_1       |     write_frame(1, channel, payload)
lustre-audit_1       | 
lustre-audit_1       |   File "/usr/lib/python2.7/site-packages/amqp/transport.py", line 182, in write_frame
lustre-audit_1       |     frame_type, channel, size, payload, 0xce,
lustre-audit_1       | 
lustre-audit_1       |   File "/usr/lib64/python2.7/socket.py", line 224, in meth
lustre-audit_1       |     return getattr(self._sock,name)(*args)
lustre-audit_1       | 
lustre-audit_1       | error: [Errno 104] Connection reset by peer
```
and
```
[2019-04-02 21:25:00,784: ERROR/chroma_core.services.lustre_audit] Error handling lustre message: Traceback (most recent call last):
lustre-audit_1       | 
lustre-audit_1       |   File "/usr/share/chroma-manager/chroma_core/services/lustre_audit/__init__.py", line 32, in on_data
lustre-audit_1       |     UpdateScan().run(host.id, data)
lustre-audit_1       | 
lustre-audit_1       |   File "/usr/share/chroma-manager/chroma_core/services/lustre_audit/update_scan.py", line 60, in run
lustre-audit_1       |     self.audit_host()
lustre-audit_1       | 
lustre-audit_1       |   File "/usr/share/chroma-manager/chroma_core/services/lustre_audit/update_scan.py", line 51, in audit_host
lustre-audit_1       |     self.update_client_mounts()
lustre-audit_1       | 
lustre-audit_1       |   File "/usr/share/chroma-manager/chroma_core/services/lustre_audit/update_scan.py", line 174, in update_client_mounts
lustre-audit_1       |     filesystem = ManagedFilesystem.objects.get(name=fsname)
lustre-audit_1       | 
lustre-audit_1       |   File "/usr/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
lustre-audit_1       |     return self.get_queryset().get(*args, **kwargs)
lustre-audit_1       | 
lustre-audit_1       |   File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 310, in get
lustre-audit_1       |     self.model._meta.object_name)
lustre-audit_1       | 
lustre-audit_1       | DoesNotExist: ManagedFilesystem matching query does not exist.
```

### iml-diagnostics
All four servers were put into debug mode before creating the filesystem without hsm (named fs2). I then deleted fs2 and created fs3 with hsm support to show that the graphs do not appear as in the images above.

[sosreport-mds1.tar.xz.zip](https://github.com/whamcloud/integrated-manager-for-lustre/files/3036576/sosreport-mds1.tar.xz.zip)
[sosreport-mds2.tar.xz.zip](https://github.com/whamcloud/integrated-manager-for-lustre/files/3036577/sosreport-mds2.tar.xz.zip)
[sosreport-oss1.tar.xz.zip](https://github.com/whamcloud/integrated-manager-for-lustre/files/3036578/sosreport-oss1.tar.xz.zip)
[sosreport-oss2.tar.xz.zip](https://github.com/whamcloud/integrated-manager-for-lustre/files/3036579/sosreport-oss2.tar.xz.zip)

**Comment by utopiabound** [comment]
c.f. whamcloud/iml-agent/pull/81
