### ISSUE TITLE
Jobs automatically cancelled

### ISSUE THREAD

**Issue by johnsonw** [whamcloud/integrated-manager-for-lustre#860]
### Description 

While creating a filesystem and working on stratagem I ran into an interesting issue in which some of the running jobs were simply cancelled for no apparent reason:

![image](https://user-images.githubusercontent.com/1100657/55832936-a04db000-5ae4-11e9-87e8-9661f0e97b97.png)

### Version

What version of IML? 5.0 (working on stratagem)
What Operating System? CentOS
What Operating System version? 7.6

### iml-diagnostics

Key traces:
## Manager
```
[2019-04-09 14:11:01,358: INFO/job] StatefulObject.set_state oss2.local LNet configuration lnet_down->lnet_up (intentional=True) 140629785651984
[2019-04-09 14:11:01,362: INFO/job] Job 95: StateChangeJob complete, setting state lnet_up on oss2.local LNet configuration
[2019-04-09 14:11:01,362: INFO/job] Job 95: not_deleted=True
[2019-04-09 14:11:01,362: INFO/job_scheduler] Job 95: complete_job: Updating cache
[2019-04-09 14:11:01,362: INFO/job_scheduler] Job 95: locked_item 140629785651984 <class 'chroma_core.models.lnet_configuration.LNetConfiguration'> True True
[2019-04-09 14:11:01,364: INFO/job_scheduler] Job 95 completing (errored=False, cancelled=False)
[2019-04-09 14:11:01,382: INFO/job_scheduler] run_next: 0 runnable jobs of (16 pending, 4 tasked)
[2019-04-09 14:15:06,108: INFO/job_scheduler] cancel_job: Cancelling job 64 (tasked)
[2019-04-09 14:15:06,127: INFO/job_scheduler] Job 64: cancelling
[2019-04-09 14:15:06,127: INFO/job_scheduler] Job 64: waiting 30s for run to complete
[2019-04-09 14:15:06,713: WARNING/chroma_core.services.job_scheduler.agent_rpc] Cancelling RPC 187ef7a8-60ab-41e2-97cc-85f8a6f130da
[2019-04-09 14:15:06,713: WARNING/chroma_core.services.job_scheduler.agent_rpc] Cancelling RPC 187ef7a8-60ab-41e2-97cc-85f8a6f130da
[2019-04-09 14:15:06,792: ERROR/job_scheduler] Job 64 step 0 encountered an error: :Traceback (most recent call last):
  File "/usr/share/chroma-manager/chroma_core/services/job_scheduler/job_scheduler.py", line 326, in _run
    result = step.run(args)
  File "/usr/share/chroma-manager/chroma_core/models/corosync2.py", line 134, in run
    config = self.invoke_agent_expect_result(corosync_configuration.host, "get_corosync_autoconfig")
  File "/usr/share/chroma-manager/chroma_core/lib/job.py", line 195, in invoke_agent_expect_result
    result = self.invoke_agent(host, command, args)
  File "/usr/share/chroma-manager/chroma_core/lib/job.py", line 185, in invoke_agent
    result, action_state = AgentRpc.call(host.fqdn, command, args, self._cancel_event)
  File "/usr/share/chroma-manager/chroma_core/services/job_scheduler/agent_rpc.py", line 357, in call
    return cls._messenger.call(fqdn, action, args, cancel_event)
  File "/usr/share/chroma-manager/chroma_core/services/job_scheduler/agent_rpc.py", line 313, in call
    return self._complete(rpc, cancel_event), rpc
  File "/usr/share/chroma-manager/chroma_core/services/job_scheduler/agent_rpc.py", line 298, in _complete
    raise AgentCancellation()
AgentCancellation

[2019-04-09 14:15:06,868: INFO/job_scheduler] Job 64: cancel completed
[2019-04-09 14:15:07,021: INFO/job_scheduler] Job 64: complete_job: Updating cache
[2019-04-09 14:15:07,021: INFO/job_scheduler] Job 64 has state complete in complete_job
[2019-04-09 14:15:07,587: INFO/job_scheduler] cancel_job: Cancelling job 67 (pending)
[2019-04-09 14:15:07,972: INFO/job_scheduler] run_next: 1 runnable jobs of (15 pending, 3 tasked)
```
and
```
[2019-04-09 15:40:57,200: ERROR/job_scheduler] Job 165: exception in get_steps: Traceback (most recent call last):
  File "/usr/share/chroma-manager/chroma_core/services/job_scheduler/job_scheduler.py", line 544, in _check_jobs
    job.steps = job.get_steps()
  File "/usr/share/chroma-manager/chroma_core/models/target.py", line 1128, in get_steps
    raise RuntimeError("Cannot register target while MGS is not started on its primary server")
RuntimeError: Cannot register target while MGS is not started on its primary server

[2019-04-09 15:40:57,200: INFO/job_scheduler] Job 165 completing (errored=False, cancelled=True)
[2019-04-09 15:40:57,688: INFO/job_scheduler] run_next: 1 runnable jobs of (15 pending, 0 tasked)
```

## Agent
```
[09/Apr/2019:15:09:23] daemon WARNING get_nids: failed to open:
[09/Apr/2019:15:09:25] daemon ERROR Unhandled error in thread HttpWriter: Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/chroma_agent/agent_client.py", line 329, in run
    self._run()

  File "/usr/lib/python2.7/site-packages/chroma_agent/agent_client.py", line 385, in _run
    self.send()

  File "/usr/lib/python2.7/site-packages/chroma_agent/agent_client.py", line 472, in send
    callback()

  File "/usr/lib/python2.7/site-packages/chroma_agent/action_plugins/manage_node.py", line 51, in _reboot
    AgentShell.try_run(["shutdown", "-r", at_time])

  File "/usr/lib/python2.7/site-packages/chroma_agent/lib/shell.py", line 110, in try_run
    raise AgentShell.CommandExecutionError(result, arg_list)

CommandExecutionError: Error (-15) running 'shutdown -r now': '' ''
```

[sosreport-adm.tar.xz.zip](https://github.com/whamcloud/integrated-manager-for-lustre/files/3060886/sosreport-adm.tar.xz.zip)
[sosreport-mds1.tar.xz.zip](https://github.com/whamcloud/integrated-manager-for-lustre/files/3060887/sosreport-mds1.tar.xz.zip)
[sosreport-mds2.tar.xz.zip](https://github.com/whamcloud/integrated-manager-for-lustre/files/3060891/sosreport-mds2.tar.xz.zip)
[sosreport-oss1.tar.xz.zip](https://github.com/whamcloud/integrated-manager-for-lustre/files/3060893/sosreport-oss1.tar.xz.zip)
[sosreport-oss2.tar.xz.zip](https://github.com/whamcloud/integrated-manager-for-lustre/files/3060894/sosreport-oss2.tar.xz.zip)

**Comment by jgrund** [comment]
Looks like this is the error: Cannot register target while MGS is not started on its primary server.

Closing this as our corosync integration had some bugfixes since this was raised.
