### ISSUE TITLE
Attempt to set primary/secondary VolumeNodes across HA clusters

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#862]
Seen in: https://build.whamcloud.com/job/integration-tests-shared-storage-configuration/1505

While creating a filesystem, the following error occurs in SSI testing:

```
test_alerts (tests.integration.shared_storage_configuration.test_alerting.TestAlerting) ... FAIL
FAIL
Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_alerting.py", line 33, in test_alerts
    fs_id = self.create_filesystem_standard(self.TEST_SERVERS)
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 343, in create_filesystem_standard
    self.set_volume_mounts(ha_volumes[2], hosts[2]["id"], hosts[3]["id"])
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 538, in set_volume_mounts
    self.assertTrue(response.successful, response.text)
AssertionError: Attempt to set primary/secondary VolumeNodes across HA clusters for Volume 3:target2

Volume Node Hosts vm7, vm8

Known HA Clusters (vm5, vm6)
```

vm7 and vm8 were not configured to use the same corosync port:

![Screen Shot 2019-04-10 at 9 18 55 AM](https://user-images.githubusercontent.com/458717/55881990-b6ee1880-5b71-11e9-9990-5717d07fecf4.png)

![Screen Shot 2019-04-10 at 9 19 02 AM](https://user-images.githubusercontent.com/458717/55881994-bb1a3600-5b71-11e9-8a6e-37c5449c9cf0.png)

**Comment by utopiabound** [comment]
[sosreport-vm3-862-2019-04-10-gccfnmc.tar.gz](https://github.com/whamcloud/integrated-manager-for-lustre/files/3064486/sosreport-vm3-862-2019-04-10-gccfnmc.tar.gz)
At 12:17 corosync is correctly configured on vm7 and vm8:
```
2019-04-10 12:17:24,434: INFO/job] invoke_agent on agent vm8 configure_network {'ring1_ipaddr': u'10.73.10.24', 'ring1_name': u'eth1', 'ring0_name': u'eth3', 'ring1_prefix': 24}
[2019-04-10 12:17:24,522: INFO/job] invoke_agent on agent vm8 configure_corosync2_stage_1 {'mcast_port': 42739, 'pcs_password': 'jH1Rv2zY9EKidbVDmPLU'}
[2019-04-10 12:17:38,709: INFO/job] invoke_agent on agent vm8 configure_corosync2_stage_2 {'ring1_name': u'eth1', 'create_cluster': True, 'mcast_port': 42739, 'new_node_fqdn': u'10.128.0.24', 'ring0_name': u'eth3', 'pcs_password': 'jH1Rv2zY9EKidbVDmPLU'}
[2019-04-10 12:17:43,489: INFO/job] invoke_agent on agent vm7 configure_network {'ring1_ipaddr': u'10.73.10.23', 'ring1_name': u'eth1', 'ring0_name': u'eth3', 'ring1_prefix': 24}
[2019-04-10 12:17:58,865: INFO/job] invoke_agent on agent vm7 configure_corosync2_stage_1 {'mcast_port': 42739, 'pcs_password': 'IDOm6i9hNzwbKbtntDvp'}
[2019-04-10 12:17:58,963: INFO/job] invoke_agent on agent vm8 start_corosync2 {}
[2019-04-10 12:18:07,228: INFO/job] invoke_agent on agent vm8 start_pacemaker {}
[2019-04-10 12:18:13,050: INFO/job] invoke_agent on agent vm8 configure_corosync2_stage_2 {'ring1_name': u'eth1', 'create_cluster': False, 'mcast_port': 42739, 'new_node_fqdn': u'10.128.0.23', 'ring0_name': u'eth3', 'pcs_password': 'IDOm6i9hNzwbKbtntDvp'}
```
But at 12:30 corosync is reconfigured (vm5/6 are okay), but vm7/8 fail to reconfigure correctly:
```
[2019-04-10 12:30:31,648: INFO/job] invoke_agent on agent vm7 device_plugin {'plugin': 'linux_network'}
[2019-04-10 12:31:13,104: INFO/job] invoke_agent on agent vm7 configure_network {'ring1_ipaddr': u'10.73.10.23', 'ring1_name': u'eth1', 'ring0_name': u'eth3', 'ring1_prefix': 24}
[2019-04-10 12:31:13,242: INFO/job] invoke_agent on agent vm7 configure_corosync2_stage_1 {'mcast_port': 58881, 'pcs_password': 'U740LXmVtbpI5X5aKHeV'}
[2019-04-10 12:31:27,479: INFO/job] invoke_agent on agent vm7 configure_corosync2_stage_2 {'ring1_name': u'eth1', 'create_cluster': True, 'mcast_port': 58881, 'new_node_fqdn': u'10.128.0.23', 'ring0_name': u'eth3', 'pcs_password': 'U740LXmVtbpI5X5aKHeV'}
[2019-04-10 12:31:47,761: INFO/job] invoke_agent on agent vm7 start_corosync2 {}
[2019-04-10 12:31:56,029: INFO/job] invoke_agent on agent vm7 start_pacemaker {}
[2019-04-10 12:32:03,212: INFO/job] invoke_agent on agent vm7 configure_pacemaker {}
[2019-04-10 12:32:15,673: INFO/job] invoke_agent on agent vm8 kernel_status {}
[2019-04-10 12:32:18,922: INFO/job] invoke_agent on agent vm8 configure_ntp {'ntp_server': 'vm3'}
[2019-04-10 12:32:18,935: INFO/job] invoke_agent on agent vm8 get_corosync_autoconfig {}
[2019-04-10 12:32:19,011: INFO/job] invoke_agent on agent vm8 load_lnet {}
[2019-04-10 12:32:20,096: INFO/job] invoke_agent on agent vm8 device_plugin {'plugin': 'linux_network'}
[2019-04-10 12:32:22,652: INFO/job] invoke_agent on agent vm8 start_lnet {}
[2019-04-10 12:32:23,834: INFO/job] invoke_agent on agent vm8 device_plugin {'plugin': 'linux_network'}
[2019-04-10 12:33:05,253: INFO/job] invoke_agent on agent vm8 configure_network {'ring1_ipaddr': u'10.73.10.24', 'ring1_name': u'eth1', 'ring0_name': u'eth3', 'ring1_prefix': 24}
[2019-04-10 12:33:05,341: INFO/job] invoke_agent on agent vm8 configure_corosync2_stage_1 {'mcast_port': 42939, 'pcs_password': '3OfxGHdDxTXBSn4v9z9l'}
```

**Comment by jgrund** [comment]
I hit this as well on a local setup, needed to remove and readd servers to get nodes on the same cluster.
